//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Facturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_pedido_x_formaPago
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdPedido { get; set; }
        public string IdTipoFormaPago { get; set; }
        public int Secuencia { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Fecha_vct { get; set; }
        public int Dias_Plazo { get; set; }
        public double Por_Distribucion { get; set; }
        public double Valor { get; set; }
    
        public virtual fa_pedido fa_pedido { get; set; }
        public virtual fa_TerminoPago fa_TerminoPago { get; set; }
    }
}
