//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Facturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFa_Total_pedidos_x_cliente_No_despachados
    {
        public int IdEmpresa { get; set; }
        public decimal IdCliente { get; set; }
        public Nullable<double> dp_total { get; set; }
    }
}
