//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Facturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_Factura_Dev
    {
        public int IdEmpresa { get; set; }
        public int IdBodega { get; set; }
        public decimal IdCbteVta { get; set; }
        public int IdSucursal { get; set; }
        public string CodCbteVta { get; set; }
        public string vt_tipoDoc { get; set; }
        public string vt_serie1 { get; set; }
        public string vt_serie2 { get; set; }
        public string vt_NumFactura { get; set; }
        public decimal IdCliente { get; set; }
        public int IdVendedor { get; set; }
        public System.DateTime vt_fecha { get; set; }
        public decimal vt_plazo { get; set; }
        public System.DateTime vt_fech_venc { get; set; }
        public string vt_tipo_venta { get; set; }
        public string vt_Observacion { get; set; }
        public int IdPeriodo { get; set; }
        public int vt_anio { get; set; }
        public int vt_mes { get; set; }
        public double vt_flete { get; set; }
        public double vt_interes { get; set; }
        public double vt_OtroValor1 { get; set; }
        public double vt_OtroValor2 { get; set; }
        public string IdUsuario { get; set; }
        public System.DateTime Fecha_Transaccion { get; set; }
        public string IdUsuarioUltModi { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string MotivoAnulacion { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
        public string Estado { get; set; }
        public string Su_Descripcion { get; set; }
        public string bo_Descripcion { get; set; }
        public double vt_Subtotal { get; set; }
        public double vt_iva { get; set; }
        public double vt_total { get; set; }
        public int Expr1 { get; set; }
        public string vt_tieneIVA { get; set; }
        public string vt_detallexItems { get; set; }
        public double vt_PrecioFinal { get; set; }
        public double vt_DescUnitario { get; set; }
        public double vt_PorDescUnitario { get; set; }
        public double vt_Precio { get; set; }
        public double vt_cantidad { get; set; }
        public decimal IdProducto { get; set; }
        public int Secuencia { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string vt_autorizacion { get; set; }
        public string Ve_Vendedor { get; set; }
        public double dv_saldo { get; set; }
        public int IdCaja { get; set; }
    }
}
