//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Facturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_cliente
    {
        public string pe_nombreCompleto { get; set; }
        public string pe_razonSocial { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string pe_direccion { get; set; }
        public string pe_telefonoOfic { get; set; }
        public string pe_fax { get; set; }
        public string pe_sexo { get; set; }
        public string pe_Naturaleza { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdCliente { get; set; }
        public decimal IdPersona { get; set; }
        public int IdSucursal { get; set; }
        public int IdVendedor { get; set; }
        public int Idtipo_cliente { get; set; }
        public string IdTipoCredito { get; set; }
        public string cl_Cat_crediticia { get; set; }
        public int cl_plazo { get; set; }
        public double cl_porcentaje_descuento { get; set; }
        public string IdCtaCble_cxc { get; set; }
        public string cl_Garante { get; set; }
        public string cl_Cell_Garante { get; set; }
        public string cl_Mail_Garante { get; set; }
        public string cl_observacion { get; set; }
        public string IdCiudad { get; set; }
        public double cl_Cupo { get; set; }
        public Nullable<decimal> IdClienteRelacionado { get; set; }
        public string cl_LocalComercial { get; set; }
        public string cl_Rep_Legal { get; set; }
        public string cl_Mail_Rep_Legal { get; set; }
        public string cl_Cell_Rep_Legal { get; set; }
        public string cl_Ger_Gen { get; set; }
        public string cl_Mail_Ger_Gen { get; set; }
        public string cl_Cell_Ger_Gen { get; set; }
        public string cl_casilla { get; set; }
        public string cl_fax { get; set; }
        public string IdActividadComercial { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> pe_fechaNacimiento { get; set; }
        public string Descripcion_Ciudad { get; set; }
        public string Su_Descripcion { get; set; }
        public string IdCtaCble_Anti { get; set; }
        public string pe_correo { get; set; }
        public string pe_casilla { get; set; }
        public string IdEstadoCivil { get; set; }
        public string pe_estado { get; set; }
        public string CodPersona { get; set; }
        public string IdTipoDocumento { get; set; }
        public string Mail_Principal { get; set; }
        public string Mail_Secundario1 { get; set; }
        public string Mail_Secundario2 { get; set; }
        public string IdCentroCosto_CXC { get; set; }
        public string IdCentroCosto_Anticipo { get; set; }
        public string IdProvincia { get; set; }
        public string IdPais { get; set; }
        public string IdCtaCble_cxc_Credito { get; set; }
        public string IdCentroCosto_CXC_Credito { get; set; }
        public int IdTipoPersona { get; set; }
        public string pe_telefonoCasa { get; set; }
        public string pe_telfono_Contacto { get; set; }
        public string pe_celular { get; set; }
        public string pe_telefonoInter { get; set; }
        public string pe_correo_secundario1 { get; set; }
        public string pe_correo_secundario2 { get; set; }
        public string pe_celularSecundario { get; set; }
        public string Codigo { get; set; }
    }
}
