//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Facturacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_clientes_contactos
    {
        public int IdEmpresa_cli { get; set; }
        public decimal IdCliente { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdContacto { get; set; }
        public string CodContacto { get; set; }
        public string Cargo { get; set; }
        public string Mostrar_como { get; set; }
        public string Notas { get; set; }
        public string Organizacion { get; set; }
        public string Pagina_Web { get; set; }
        public string Codigo_postal { get; set; }
        public string Estado { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public string IdTipoDocumento { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string pe_direccion { get; set; }
        public string pe_telefonoCasa { get; set; }
        public string pe_celular { get; set; }
        public string pe_correo { get; set; }
        public string pe_sexo { get; set; }
        public Nullable<System.DateTime> pe_fechaNacimiento { get; set; }
        public decimal IdPersona { get; set; }
        public System.DateTime Fecha_alta { get; set; }
        public System.DateTime Fecha_Ult_Contacto { get; set; }
        public string IdPais { get; set; }
        public string Nombre { get; set; }
        public string IdProvincia { get; set; }
        public string Descripcion_Prov { get; set; }
        public string IdCiudad { get; set; }
        public string Descripcion_Ciudad { get; set; }
        public string IdNacionalidad { get; set; }
        public string Nacionalidad { get; set; }
        public string pe_razonSocial { get; set; }
        public string pe_Naturaleza { get; set; }
    }
}
