//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.Naturisa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesContabilidad_Natu_Rpt : DbContext
    {
        public EntitiesContabilidad_Natu_Rpt()
            : base("name=EntitiesContabilidad_Natu_Rpt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwCONTA_NATU_Rpt002> vwCONTA_NATU_Rpt002 { get; set; }
        public DbSet<vwCONTA_NATU_Rpt003> vwCONTA_NATU_Rpt003 { get; set; }
    }
}
