//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.Naturisa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesCompras_natu_rpt : DbContext
    {
        public EntitiesCompras_natu_rpt()
            : base("name=EntitiesCompras_natu_rpt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwCOMP_NATU_Rpt002> vwCOMP_NATU_Rpt002 { get; set; }
        public DbSet<vwCOMP_NATU_Rpt004> vwCOMP_NATU_Rpt004 { get; set; }
        public DbSet<vwCOMP_Rpt001> vwCOMP_Rpt001 { get; set; }
        public DbSet<vwCOMP_NATU_Rpt007> vwCOMP_NATU_Rpt007 { get; set; }
        public DbSet<vwCOMP_NATU_Rpt003> vwCOMP_NATU_Rpt003 { get; set; }
        public DbSet<vwCONTA_NATU_Rpt003> vwCONTA_NATU_Rpt003 { get; set; }
        public DbSet<vwCOMP_Rpt003> vwCOMP_Rpt003 { get; set; }
        public DbSet<vwCOMP_Rpt002> vwCOMP_Rpt002 { get; set; }
        public DbSet<vwCOMP_NATU_Rpt001> vwCOMP_NATU_Rpt001 { get; set; }
    }
}
