public enum ebanco_procesos_bancarios_tipo
{ 
     PAGO_BANCO_PACIFICO_BPA
    ,PAGO_PROVEEDORES_BOL
    ,PAGO_PROVEEDORES_BP
    ,PREAVISO_CHEQ
    ,ROL_ELECTRONICO_BG
    ,TRANSF_BANCARIA_BP
    , MASTERCARD_BOLIVARIANO
    , DINER_PICHINCHA
    ,BANCO_INTERNACIONAL
    ,PACIFICAR,
    PAGOS_MULTICASH,
    NCR,
    NCR_OTROS_BCO,
    //CAH
    DEB_CTA_CTE_AHO_BB
}