//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.ERP.Reports.Grafinpren
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntitiesCuentasxCobrar_GRAF_Rpt : DbContext
    {
        public EntitiesCuentasxCobrar_GRAF_Rpt()
            : base("name=EntitiesCuentasxCobrar_GRAF_Rpt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwCXC_GRAF_Rpt001> vwCXC_GRAF_Rpt001 { get; set; }
        public DbSet<vwCXC_GRAF_Rpt003> vwCXC_GRAF_Rpt003 { get; set; }
    
        public virtual ObjectResult<spCXC_GRAF_Rpt002_Result> spCXC_GRAF_Rpt002(Nullable<int> idEmpresa, Nullable<decimal> idClienteIni, Nullable<decimal> idClienteFin, Nullable<decimal> idVendedorIni, Nullable<decimal> idVendedorFin, Nullable<System.DateTime> fechaCorte)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var idClienteIniParameter = idClienteIni.HasValue ?
                new ObjectParameter("IdClienteIni", idClienteIni) :
                new ObjectParameter("IdClienteIni", typeof(decimal));
    
            var idClienteFinParameter = idClienteFin.HasValue ?
                new ObjectParameter("IdClienteFin", idClienteFin) :
                new ObjectParameter("IdClienteFin", typeof(decimal));
    
            var idVendedorIniParameter = idVendedorIni.HasValue ?
                new ObjectParameter("IdVendedorIni", idVendedorIni) :
                new ObjectParameter("IdVendedorIni", typeof(decimal));
    
            var idVendedorFinParameter = idVendedorFin.HasValue ?
                new ObjectParameter("IdVendedorFin", idVendedorFin) :
                new ObjectParameter("IdVendedorFin", typeof(decimal));
    
            var fechaCorteParameter = fechaCorte.HasValue ?
                new ObjectParameter("FechaCorte", fechaCorte) :
                new ObjectParameter("FechaCorte", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCXC_GRAF_Rpt002_Result>("spCXC_GRAF_Rpt002", idEmpresaParameter, idClienteIniParameter, idClienteFinParameter, idVendedorIniParameter, idVendedorFinParameter, fechaCorteParameter);
        }
    }
}
