//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.ERP.Reports.Grafinpren
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesFacturacion_Rpt_GRAF : DbContext
    {
        public EntitiesFacturacion_Rpt_GRAF()
            : base("name=EntitiesFacturacion_Rpt_GRAF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwFAC_GRAF_Rpt001> vwFAC_GRAF_Rpt001 { get; set; }
        public DbSet<vwFAC_GRAF_Rpt002> vwFAC_GRAF_Rpt002 { get; set; }
    }
}
