//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_ListadoMateriales_Det
    {
        public com_ListadoMateriales_Det()
        {
            this.com_cotizacion_compra_det = new HashSet<com_cotizacion_compra_det>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdListadoMateriales { get; set; }
        public int IdDetalle { get; set; }
        public string CodObra { get; set; }
        public Nullable<decimal> IdOrdenTaller { get; set; }
        public decimal IdProducto { get; set; }
        public double Unidades { get; set; }
        public double Det_Kg { get; set; }
        public Nullable<double> pr_largo { get; set; }
        public Nullable<double> largo_total { get; set; }
        public Nullable<double> largo_restante { get; set; }
        public Nullable<double> largo_pieza_entera { get; set; }
        public Nullable<int> cantidad_pieza_entera { get; set; }
        public Nullable<double> largo_pieza_complementaria { get; set; }
        public Nullable<double> cantidad_pieza_complementaria { get; set; }
        public Nullable<double> cantidad_total_pieza_complementaria { get; set; }
        public Nullable<double> largo_despunte1 { get; set; }
        public Nullable<double> cantidad_despunte1 { get; set; }
        public Nullable<bool> es_despunte_usable1 { get; set; }
        public Nullable<double> largo_despunte2 { get; set; }
        public Nullable<double> cantidad_despunte2 { get; set; }
        public Nullable<bool> es_despunte_usable2 { get; set; }
        public string IdEstadoAprob { get; set; }
    
        public virtual ICollection<com_cotizacion_compra_det> com_cotizacion_compra_det { get; set; }
    }
}
