//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_archivos_para_banco_x_cxp
    {
        public cp_archivos_para_banco_x_cxp()
        {
            this.cp_archivos_para_banco_x_cxp_det = new HashSet<cp_archivos_para_banco_x_cxp_det>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdArchivo { get; set; }
        public int IdBanco { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Cod_Empresa { get; set; }
        public string Tipo { get; set; }
        public string Nom_Archivo { get; set; }
        public byte[] archivo { get; set; }
        public string estado { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string observacion { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
        public string Motivo_anulacion { get; set; }
    
        public virtual ICollection<cp_archivos_para_banco_x_cxp_det> cp_archivos_para_banco_x_cxp_det { get; set; }
    }
}
