//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_catalogo
    {
        public cp_catalogo()
        {
            this.cp_conciliacion_Caja = new HashSet<cp_conciliacion_Caja>();
            this.cp_nota_DebCre = new HashSet<cp_nota_DebCre>();
            this.cp_proveedor = new HashSet<cp_proveedor>();
            this.cp_proveedor1 = new HashSet<cp_proveedor>();
            this.cp_proveedor2 = new HashSet<cp_proveedor>();
        }
    
        public string IdCatalogo { get; set; }
        public string IdCatalogo_tipo { get; set; }
        public string Nombre { get; set; }
        public string Estado { get; set; }
        public string Abrebiatura { get; set; }
        public string NombreIngles { get; set; }
        public Nullable<int> Orden { get; set; }
        public string IdUsuario { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> FechaUltMod { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
    
        public virtual cp_catalogo_tipo cp_catalogo_tipo { get; set; }
        public virtual ICollection<cp_conciliacion_Caja> cp_conciliacion_Caja { get; set; }
        public virtual ICollection<cp_nota_DebCre> cp_nota_DebCre { get; set; }
        public virtual ICollection<cp_proveedor> cp_proveedor { get; set; }
        public virtual ICollection<cp_proveedor> cp_proveedor1 { get; set; }
        public virtual ICollection<cp_proveedor> cp_proveedor2 { get; set; }
    }
}
