//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_catalogo_tipo
    {
        public cp_catalogo_tipo()
        {
            this.cp_catalogo = new HashSet<cp_catalogo>();
        }
    
        public string IdCatalogo_tipo { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<cp_catalogo> cp_catalogo { get; set; }
    }
}
