//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_distribucion_gastos_x_periodo_det_ct_punto_cargo
    {
        public int IdEmpresa { get; set; }
        public decimal IdDistribucion { get; set; }
        public int Secuencia { get; set; }
        public int IdPunto_cargo { get; set; }
        public double Porcentaje { get; set; }
        public bool Checked { get; set; }
    
        public virtual ct_distribucion_gastos_x_periodo ct_distribucion_gastos_x_periodo { get; set; }
    }
}
