//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_grupocble_Mayor
    {
        public ct_grupocble_Mayor()
        {
            this.ct_grupocble = new HashSet<ct_grupocble>();
        }
    
        public string IdGrupo_Mayor { get; set; }
        public string nom_grupo_mayor { get; set; }
        public int orden { get; set; }
    
        public virtual ICollection<ct_grupocble> ct_grupocble { get; set; }
    }
}
