//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_GrupoEmpresarial_plancta_x_ct_plancta
    {
        public string IdGrupoEmpresarial { get; set; }
        public string IdCuenta_gr { get; set; }
        public int IdEmpresa { get; set; }
        public string IdCtaCble { get; set; }
    
        public virtual ct_GrupoEmpresarial ct_GrupoEmpresarial { get; set; }
        public virtual ct_GrupoEmpresarial_plancta ct_GrupoEmpresarial_plancta { get; set; }
        public virtual ct_plancta ct_plancta { get; set; }
    }
}
