//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_cliente_pto_emision_cliente
    {
        public int IdEmpresa { get; set; }
        public decimal IdCliente { get; set; }
        public int IdPuntoEmision { get; set; }
        public string cod_ptoemision { get; set; }
        public string ruc { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string mail1 { get; set; }
        public string mail2 { get; set; }
        public string Estado { get; set; }
    }
}
