//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_liquidacion_gastos_producto
    {
        public fa_liquidacion_gastos_producto()
        {
            this.fa_liquidacion_gastos_det = new HashSet<fa_liquidacion_gastos_det>();
            this.fa_liquidaciones_tipo_proceso = new HashSet<fa_liquidaciones_tipo_proceso>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdProducto_Liqui { get; set; }
        public string nom_producto_Liqui { get; set; }
        public string estado { get; set; }
        public decimal IdProducto { get; set; }
    
        public virtual ICollection<fa_liquidacion_gastos_det> fa_liquidacion_gastos_det { get; set; }
        public virtual ICollection<fa_liquidaciones_tipo_proceso> fa_liquidaciones_tipo_proceso { get; set; }
    }
}
