//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_liquidaciones_det
    {
        public int IdEmpresa { get; set; }
        public decimal IdLiquidaciones { get; set; }
        public int Secuencia { get; set; }
        public Nullable<int> IdEmpresa_liqui_gastos { get; set; }
        public Nullable<decimal> IdLiquidacion_liqui_gastos { get; set; }
    }
}
