//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class imp_ordencompra_ext_x_imp_gastosxImport
    {
        public imp_ordencompra_ext_x_imp_gastosxImport()
        {
            this.imp_ordencompra_ext_x_imp_gastosxImport_det = new HashSet<imp_ordencompra_ext_x_imp_gastosxImport_det>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdRegistroGasto { get; set; }
        public int IdSucusal { get; set; }
        public decimal IdOrdenCompraExt { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observacion { get; set; }
        public Nullable<decimal> IdProveedor { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public string CodDocu_Pago { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdTipoCbte { get; set; }
        public Nullable<decimal> IdCbteCble { get; set; }
        public Nullable<int> IdTipoCbte_Anu { get; set; }
        public Nullable<decimal> IdCbteCble_Anu { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
    
        public virtual imp_ordencompra_ext imp_ordencompra_ext { get; set; }
        public virtual ICollection<imp_ordencompra_ext_x_imp_gastosxImport_det> imp_ordencompra_ext_x_imp_gastosxImport_det { get; set; }
    }
}
