//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class imp_gastosxImport_x_Empresa
    {
        public int IdEmpresa { get; set; }
        public int IdGastoImp { get; set; }
        public string IdCtaCble { get; set; }
        public string debcre_DebBanco { get; set; }
        public string debCre_Provicion { get; set; }
        public string AfectaLiquidacion { get; set; }
    
        public virtual imp_gastosxImport imp_gastosxImport { get; set; }
    }
}
