//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_egreso_d_Suministro
    {
        public int IdEmpresa { get; set; }
        public int IdSucursa { get; set; }
        public int IdBodega { get; set; }
        public decimal IdEgresoSumin { get; set; }
        public decimal IdGasto { get; set; }
        public decimal IdCentroDeCosto { get; set; }
        public Nullable<decimal> IdProducto { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> Subtotal { get; set; }
        public string observacion { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transa { get; set; }
        public string IdUsuarioUltModi { get; set; }
        public Nullable<System.DateTime> FechaUltModi { get; set; }
        public string IdUsuarioAnula { get; set; }
        public Nullable<System.DateTime> FechaAnula { get; set; }
        public string Estado { get; set; }
    }
}
