//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_Guia_x_traspaso_bodega_det_sin_oc
    {
        public int IdEmpresa { get; set; }
        public decimal IdGuia { get; set; }
        public int secuencia { get; set; }
        public string Num_Fact { get; set; }
        public Nullable<decimal> IdProveedor { get; set; }
        public string nom_proveedor { get; set; }
        public Nullable<decimal> IdProducto { get; set; }
        public string nom_producto { get; set; }
        public double Cantidad_enviar { get; set; }
        public string observacion { get; set; }
    
        public virtual in_Producto in_Producto { get; set; }
        public virtual in_Guia_x_traspaso_bodega in_Guia_x_traspaso_bodega { get; set; }
    }
}
