//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_Guia_x_traspaso_bodega_x_in_transferencia_det
    {
        public int IdEmpresa { get; set; }
        public decimal IdGuia { get; set; }
        public int IdEmpresa_tras { get; set; }
        public int IdSucursalOrigen { get; set; }
        public int IdBodegaOrigen { get; set; }
        public decimal IdTransferencia { get; set; }
        public int dt_secuencia { get; set; }
        public decimal cantidad { get; set; }
        public string observacion { get; set; }
    
        public virtual in_transferencia_det in_transferencia_det { get; set; }
        public virtual in_Guia_x_traspaso_bodega in_Guia_x_traspaso_bodega { get; set; }
    }
}
