//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_producto_x_cp_proveedor
    {
        public int IdEmpresa_prod { get; set; }
        public decimal IdProducto { get; set; }
        public int IdEmpresa_prov { get; set; }
        public decimal IdProveedor { get; set; }
        public string NomProducto_en_Proveedor { get; set; }
    
        public virtual in_Producto in_Producto { get; set; }
    }
}
