//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntitiesGeneral : DbContext
    {
        public EntitiesGeneral()
            : base("name=EntitiesGeneral")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_Calendario> tb_Calendario { get; set; }
        public DbSet<tb_Catalogo> tb_Catalogo { get; set; }
        public DbSet<tb_CatalogoTipo> tb_CatalogoTipo { get; set; }
        public DbSet<tb_ciudad> tb_ciudad { get; set; }
        public DbSet<tb_contacto> tb_contacto { get; set; }
        public DbSet<tb_dia> tb_dia { get; set; }
        public DbSet<tb_mes> tb_mes { get; set; }
        public DbSet<tb_moneda> tb_moneda { get; set; }
        public DbSet<tb_pais> tb_pais { get; set; }
        public DbSet<tb_parametro> tb_parametro { get; set; }
        public DbSet<tb_parametro_tipo> tb_parametro_tipo { get; set; }
        public DbSet<tb_persona> tb_persona { get; set; }
        public DbSet<tb_persona_direccion> tb_persona_direccion { get; set; }
        public DbSet<tb_persona_direccion_tipo> tb_persona_direccion_tipo { get; set; }
        public DbSet<tb_persona_tipo> tb_persona_tipo { get; set; }
        public DbSet<tb_provincia> tb_provincia { get; set; }
        public DbSet<tb_rango_fecha_busqueda_x_periodo> tb_rango_fecha_busqueda_x_periodo { get; set; }
        public DbSet<tb_sis_Datos_Sistema> tb_sis_Datos_Sistema { get; set; }
        public DbSet<tb_sis_Documento_Registros_x_Talonario> tb_sis_Documento_Registros_x_Talonario { get; set; }
        public DbSet<tb_sis_Documento_Tipo> tb_sis_Documento_Tipo { get; set; }
        public DbSet<tb_sis_Documento_Tipo_Reporte_x_Empresa> tb_sis_Documento_Tipo_Reporte_x_Empresa { get; set; }
        public DbSet<tb_sis_Documento_Tipo_x_Empresa> tb_sis_Documento_Tipo_x_Empresa { get; set; }
        public DbSet<tb_sis_Documento_Tipo_x_Empresa_Anulados> tb_sis_Documento_Tipo_x_Empresa_Anulados { get; set; }
        public DbSet<tb_sis_Documento_Tipo_x_Secuencia_Talonario> tb_sis_Documento_Tipo_x_Secuencia_Talonario { get; set; }
        public DbSet<tb_sis_Grupo_empresarial_Cliente> tb_sis_Grupo_empresarial_Cliente { get; set; }
        public DbSet<tb_sis_iconos> tb_sis_iconos { get; set; }
        public DbSet<tb_sis_Log_Error_Vzen> tb_sis_Log_Error_Vzen { get; set; }
        public DbSet<tb_sis_Mensajes_sys> tb_sis_Mensajes_sys { get; set; }
        public DbSet<tb_sis_reporte> tb_sis_reporte { get; set; }
        public DbSet<tb_sis_reporte_Grupo> tb_sis_reporte_Grupo { get; set; }
        public DbSet<tb_sucursal> tb_sucursal { get; set; }
        public DbSet<tb_tarjeta> tb_tarjeta { get; set; }
        public DbSet<tb_tarjeta_parametro> tb_tarjeta_parametro { get; set; }
        public DbSet<vw_EstadoCivil> vw_EstadoCivil { get; set; }
        public DbSet<vw_NaturalezaPersona> vw_NaturalezaPersona { get; set; }
        public DbSet<vw_Persona> vw_Persona { get; set; }
        public DbSet<vw_TipoDocumento> vw_TipoDocumento { get; set; }
        public DbSet<vw_usuario> vw_usuario { get; set; }
        public DbSet<vwGe_tb_sis_Mensajes_sys_IdAuto_numeric> vwGe_tb_sis_Mensajes_sys_IdAuto_numeric { get; set; }
        public DbSet<vwGe_tb_Tarjeta_tb_Parametro> vwGe_tb_Tarjeta_tb_Parametro { get; set; }
        public DbSet<vwtb_Bodega_x_Sucursal_TreeList> vwtb_Bodega_x_Sucursal_TreeList { get; set; }
        public DbSet<vwtb_Ciudad> vwtb_Ciudad { get; set; }
        public DbSet<vwtb_contacto> vwtb_contacto { get; set; }
        public DbSet<vwtb_persona_beneficiario> vwtb_persona_beneficiario { get; set; }
        public DbSet<vwtb_persona_beneficiario_por_Banco_Acreditacion> vwtb_persona_beneficiario_por_Banco_Acreditacion { get; set; }
        public DbSet<vwtb_sis_Documento_Tipo_x_Disenio_Report> vwtb_sis_Documento_Tipo_x_Disenio_Report { get; set; }
        public DbSet<vwtb_transportista_x_tb_persona> vwtb_transportista_x_tb_persona { get; set; }
        public DbSet<vwtb_Ubicacion_Geografica> vwtb_Ubicacion_Geografica { get; set; }
        public DbSet<tb_sis_Documento_Tipo_Talonario> tb_sis_Documento_Tipo_Talonario { get; set; }
        public DbSet<vwGe_tb_sis_Documento_Tipo_Talonario> vwGe_tb_sis_Documento_Tipo_Talonario { get; set; }
        public DbSet<tb_sis_Impuesto> tb_sis_Impuesto { get; set; }
        public DbSet<tbSys_Ge_Comparativo_Modulo_vs_Contas> tbSys_Ge_Comparativo_Modulo_vs_Contas { get; set; }
        public DbSet<tb_parroquia> tb_parroquia { get; set; }
        public DbSet<vwtb_empresa_x_Usuario> vwtb_empresa_x_Usuario { get; set; }
        public DbSet<tb_sis_Impuesto_Tipo> tb_sis_Impuesto_Tipo { get; set; }
        public DbSet<tb_sis_Impuesto_x_ctacble> tb_sis_Impuesto_x_ctacble { get; set; }
        public DbSet<tb_modulo> tb_modulo { get; set; }
        public DbSet<tb_bodega> tb_bodega { get; set; }
        public DbSet<tb_sis_reporte_x_formulario> tb_sis_reporte_x_formulario { get; set; }
        public DbSet<tb_sis_formulario> tb_sis_formulario { get; set; }
        public DbSet<tb_banco_procesos_bancarios_tipo> tb_banco_procesos_bancarios_tipo { get; set; }
        public DbSet<tb_banco> tb_banco { get; set; }
        public DbSet<tb_banco_procesos_bancarios_x_empresa> tb_banco_procesos_bancarios_x_empresa { get; set; }
        public DbSet<vwtb_tb_banco_procesos_bancarios> vwtb_tb_banco_procesos_bancarios { get; set; }
        public DbSet<tb_transportista> tb_transportista { get; set; }
        public DbSet<tb_empresa> tb_empresa { get; set; }
        public DbSet<vwtb_sis_Documento_Tipo_x_Empresa_Anulados> vwtb_sis_Documento_Tipo_x_Empresa_Anulados { get; set; }
        public DbSet<tb_banco_estado_reg__resp_bancaria> tb_banco_estado_reg__resp_bancaria { get; set; }
    
        public virtual ObjectResult<spSys_ObtenerFecha_SinFeriadoTampocoSabDom_Result> spSys_ObtenerFecha_SinFeriadoTampocoSabDom(Nullable<System.DateTime> fechaInicial, Nullable<int> dias)
        {
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("FechaInicial", fechaInicial) :
                new ObjectParameter("FechaInicial", typeof(System.DateTime));
    
            var diasParameter = dias.HasValue ?
                new ObjectParameter("Dias", dias) :
                new ObjectParameter("Dias", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSys_ObtenerFecha_SinFeriadoTampocoSabDom_Result>("spSys_ObtenerFecha_SinFeriadoTampocoSabDom", fechaInicialParameter, diasParameter);
        }
    
        public virtual ObjectResult<spSys_Ge_Comparativo_Modulo_vs_Contas_Result> spSys_Ge_Comparativo_Modulo_vs_Contas(Nullable<int> i_IdEmpresa, Nullable<System.DateTime> i_fecha_ini, Nullable<System.DateTime> i_fecha_fin)
        {
            var i_IdEmpresaParameter = i_IdEmpresa.HasValue ?
                new ObjectParameter("i_IdEmpresa", i_IdEmpresa) :
                new ObjectParameter("i_IdEmpresa", typeof(int));
    
            var i_fecha_iniParameter = i_fecha_ini.HasValue ?
                new ObjectParameter("i_fecha_ini", i_fecha_ini) :
                new ObjectParameter("i_fecha_ini", typeof(System.DateTime));
    
            var i_fecha_finParameter = i_fecha_fin.HasValue ?
                new ObjectParameter("i_fecha_fin", i_fecha_fin) :
                new ObjectParameter("i_fecha_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSys_Ge_Comparativo_Modulo_vs_Contas_Result>("spSys_Ge_Comparativo_Modulo_vs_Contas", i_IdEmpresaParameter, i_fecha_iniParameter, i_fecha_finParameter);
        }
    }
}
