//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class prd_GruposTrabajo_PorPP
    {
        public int IdProcesoProductivo { get; set; }
        public int IdEtapa { get; set; }
        public int IdGrupoTrabajo { get; set; }
        public int IdSubgrupo { get; set; }
    }
}
