//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pre_presupuesto_tipoRubro
    {
        public pre_presupuesto_tipoRubro()
        {
            this.pre_presupuesto = new HashSet<pre_presupuesto>();
        }
    
        public string IdTipoRubro { get; set; }
        public string Descripcion { get; set; }
        public string Tabla { get; set; }
    
        public virtual ICollection<pre_presupuesto> pre_presupuesto { get; set; }
    }
}
