//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class prod_LiquidacionChatarraDetalle
    {
        public int IdEmpresa { get; set; }
        public decimal IdLiquidacion { get; set; }
        public int Secuencia { get; set; }
        public Nullable<double> LLeno { get; set; }
        public Nullable<double> Vacio { get; set; }
        public Nullable<double> Merma { get; set; }
        public Nullable<double> Neta { get; set; }
        public Nullable<System.DateTime> fecha_pesaje_lleno { get; set; }
        public Nullable<System.DateTime> fecha_pesaje_vacion { get; set; }
        public string Placa { get; set; }
    }
}
