//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class prod_ParametrosAceria
    {
        public int IdEmpresa { get; set; }
        public Nullable<int> IdSucursalEgresoMovi { get; set; }
        public Nullable<int> IdBodegaEgresoMovi { get; set; }
        public Nullable<int> IdMoviInvenTipoEgreso { get; set; }
        public Nullable<int> IdSucursalIngresoMovi { get; set; }
        public Nullable<int> IdBodegaIngresoMovi { get; set; }
        public Nullable<int> IdMoviInvenTipoIngreso { get; set; }
    }
}
