//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_dias
    {
        public int Id_dia { get; set; }
        public string sdia { get; set; }
        public string nemonico { get; set; }
        public Nullable<int> sdia_completo_a_partir_de { get; set; }
    }
}
