//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_fectividad_x_empleado_Adm_x_periodo_Det
    {
        public int IdEmpresa { get; set; }
        public int IdNomina_Tipo { get; set; }
        public int IdNomina_Tipo_Liq { get; set; }
        public int IdPeriodo { get; set; }
        public decimal IdEmpleado { get; set; }
        public string cod_Pago_Variable { get; set; }
        public Nullable<double> Meta { get; set; }
        public Nullable<double> Real { get; set; }
        public Nullable<double> Cumplimiento { get; set; }
        public Nullable<double> Variable_porcentaje_prorrateado { get; set; }
    
        public virtual ro_fectividad_x_empleado_Adm_x_periodo ro_fectividad_x_empleado_Adm_x_periodo { get; set; }
        public virtual ro_parametro_x_pago_variable_tipo ro_parametro_x_pago_variable_tipo { get; set; }
    }
}
