//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_Grupo_empleado
    {
        public ro_Grupo_empleado()
        {
            this.ro_Grupo_empleado_det = new HashSet<ro_Grupo_empleado_det>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdGrupo { get; set; }
        public string Nombre_Grupo { get; set; }
        public int Calculo_Horas_extras_Sobre { get; set; }
        public int Max_num_horas_sab_dom { get; set; }
        public string IdRubro_Alim { get; set; }
        public string IdRubro_Trans { get; set; }
        public double Valor_Alimen { get; set; }
        public double Valor_Transp { get; set; }
        public double Valor_bono { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
        public string Estado { get; set; }
        public string MotiAnula { get; set; }
    
        public virtual ICollection<ro_Grupo_empleado_det> ro_Grupo_empleado_det { get; set; }
    }
}
