//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_horario
    {
        public ro_horario()
        {
            this.ro_empleado_x_horario = new HashSet<ro_empleado_x_horario>();
            this.ro_horario_planificacion = new HashSet<ro_horario_planificacion>();
            this.ro_nomina_x_horas_extras = new HashSet<ro_nomina_x_horas_extras>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdHorario { get; set; }
        public Nullable<System.TimeSpan> HoraIni { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
        public Nullable<int> ToleranciaEnt { get; set; }
        public Nullable<int> ToleranciaSal { get; set; }
        public string Estado { get; set; }
        public Nullable<System.TimeSpan> InicioEntrada { get; set; }
        public Nullable<System.TimeSpan> FinalEntrada { get; set; }
        public Nullable<System.TimeSpan> InicioSal { get; set; }
        public Nullable<System.TimeSpan> FinalSalida { get; set; }
        public Nullable<System.TimeSpan> SalLunch { get; set; }
        public Nullable<System.TimeSpan> RegLunch { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> MinLunch { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
        public string MotiAnula { get; set; }
        public Nullable<int> Tolerancia_Hora { get; set; }
        public Nullable<int> Tolerancia_Minuto { get; set; }
    
        public virtual ICollection<ro_empleado_x_horario> ro_empleado_x_horario { get; set; }
        public virtual ICollection<ro_horario_planificacion> ro_horario_planificacion { get; set; }
        public virtual ICollection<ro_nomina_x_horas_extras> ro_nomina_x_horas_extras { get; set; }
    }
}
