//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_Ing_Egre_x_Empleado
    {
        public int IdEmpresa { get; set; }
        public decimal IdEmpleado { get; set; }
        public int IdNomina_Tipo { get; set; }
        public int IdNomina_TipoLiqui { get; set; }
        public int IdPeriodo { get; set; }
        public string IdRubro { get; set; }
        public decimal IdNovedad { get; set; }
        public int SecuenciaNovedad { get; set; }
        public decimal IdPrestamo { get; set; }
        public decimal NunCouta { get; set; }
        public string IngEgr { get; set; }
        public double Valor { get; set; }
        public int iAnio { get; set; }
        public int iMes { get; set; }
        public string cerrado { get; set; }
        public string observacionesSys { get; set; }
        public string TipoRegistro { get; set; }
        public string Unid_Medida { get; set; }
    
        public virtual ro_Nomina_Tipoliqui ro_Nomina_Tipoliqui { get; set; }
        public virtual ro_empleado ro_empleado { get; set; }
        public virtual ro_periodo ro_periodo { get; set; }
    }
}
