//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_Nomina_Tipoliqui_x_Sueldo
    {
        public int IdEmpresa { get; set; }
        public int IdNomina_Tipo { get; set; }
        public int IdNomina_TipoLiqui { get; set; }
        public double PorSueldo { get; set; }
        public Nullable<bool> PermiteAcumularDecimoTercer { get; set; }
        public Nullable<bool> PermiteAcumularDecimoCuarto { get; set; }
        public Nullable<bool> PermiteAcumularFondoReserva { get; set; }
    }
}
