//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_sala
    {
        public ro_sala()
        {
            this.ro_marcaciones_x_empleado_x_incidentes_falt_Perm = new HashSet<ro_marcaciones_x_empleado_x_incidentes_falt_Perm>();
        }
    
        public int IdEmpresa { get; set; }
        public int IdSala { get; set; }
        public string Sala { get; set; }
        public bool Estado { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transaccion { get; set; }
        public string IdUsuarioUltModi { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string MotivoAnulacion { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
    
        public virtual ICollection<ro_marcaciones_x_empleado_x_incidentes_falt_Perm> ro_marcaciones_x_empleado_x_incidentes_falt_Perm { get; set; }
    }
}
