//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_turno
    {
        public ro_turno()
        {
            this.ro_nomina_x_horas_extras = new HashSet<ro_nomina_x_horas_extras>();
            this.ro_turno_x_tb_dia = new HashSet<ro_turno_x_tb_dia>();
        }
    
        public int IdEmpresa { get; set; }
        public decimal IdTurno { get; set; }
        public string tu_descripcion { get; set; }
        public string Estado { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
        public string MotiAnula { get; set; }
        public Nullable<bool> es_jornada_desfasada { get; set; }
    
        public virtual ICollection<ro_nomina_x_horas_extras> ro_nomina_x_horas_extras { get; set; }
        public virtual ICollection<ro_turno_x_tb_dia> ro_turno_x_tb_dia { get; set; }
    }
}
