//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_banco_procesos_bancarios
    {
        public tb_banco_procesos_bancarios()
        {
            this.tb_banco_procesos_bancarios_x_empresa = new HashSet<tb_banco_procesos_bancarios_x_empresa>();
        }
    
        public string IdProceso_bancario { get; set; }
        public string nom_proceso_bancario { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<tb_banco_procesos_bancarios_x_empresa> tb_banco_procesos_bancarios_x_empresa { get; set; }
    }
}
