//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_Param_Cont_x_Proceso
    {
        public tb_sis_Param_Cont_x_Proceso()
        {
            this.tb_sis_Param_Cont_x_Proceso_Parametro = new HashSet<tb_sis_Param_Cont_x_Proceso_Parametro>();
        }
    
        public string IdProcesoConta { get; set; }
        public string Descripcion { get; set; }
        public string TomarParametrosContablesDE { get; set; }
        public string IdTipo_Conta { get; set; }
    
        public virtual tb_sis_Param_Cont_Tipo_Contabilizacion tb_sis_Param_Cont_Tipo_Contabilizacion { get; set; }
        public virtual ICollection<tb_sis_Param_Cont_x_Proceso_Parametro> tb_sis_Param_Cont_x_Proceso_Parametro { get; set; }
    }
}
