//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_Documento_Tipo_x_Empresa_Anulados
    {
        public int IdEmpresa { get; set; }
        public string codDocumentoTipo { get; set; }
        public decimal IdTipoDocAnu { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Serie1 { get; set; }
        public string Serie2 { get; set; }
        public string Documento { get; set; }
        public string Autorizacion { get; set; }
        public int IdMotivoAnu { get; set; }
        public string MotivoAnu { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
    }
}
