//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCXP_Rpt006
    {
        public int IdEmpresa { get; set; }
        public string IdUsuario { get; set; }
        public string nom_pc { get; set; }
        public string nDoc { get; set; }
        public string NAutorizacion { get; set; }
        public string Documento { get; set; }
        public decimal IdProveedor { get; set; }
        public decimal IdCbte { get; set; }
        public int secuencia { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaVence { get; set; }
        public string pr_CedulaRuc { get; set; }
        public string Proveedor { get; set; }
        public string Observacion { get; set; }
        public Nullable<double> SubtotalIva { get; set; }
        public Nullable<double> SubtotalSinIva { get; set; }
        public Nullable<double> baseImponible { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<System.DateTime> FechaCbte { get; set; }
    }
}
