//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Seg_Menu_x_Usuario_x_Empresa
    {
        public int IdMenu { get; set; }
        public Nullable<int> IdMenuPadre { get; set; }
        public string DescripcionMenu { get; set; }
        public int PosicionMenu { get; set; }
        public bool Habilitado { get; set; }
        public bool Tiene_FormularioAsociado { get; set; }
        public string nom_Formulario { get; set; }
        public string nom_Asembly { get; set; }
        public byte[] imagen_grande { get; set; }
        public byte[] imagen_peque { get; set; }
        public byte[] icono { get; set; }
        public Nullable<int> nivel { get; set; }
        public int IdEmpresa { get; set; }
        public string IdUsuario { get; set; }
        public bool Eliminacion { get; set; }
        public bool Escritura { get; set; }
        public bool Lectura { get; set; }
    }
}
