//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAf_Activo_fijo_Categoria
    {
        public int IdEmpresa { get; set; }
        public int IdCategoriaAF { get; set; }
        public string Descripcion { get; set; }
        public string CodCategoriaAF { get; set; }
        public int IdActivoFijoTipo { get; set; }
        public string Af_Descripcion { get; set; }
        public string Estado { get; set; }
    }
}
