//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwba_Conciliacion
    {
        public int IdEmpresa { get; set; }
        public decimal IdConciliacion { get; set; }
        public int IdBanco { get; set; }
        public int IdPeriodo { get; set; }
        public System.DateTime co_Fecha { get; set; }
        public double co_SaldoContable_MesAnt { get; set; }
        public double co_totalIng { get; set; }
        public double co_totalEgr { get; set; }
        public double co_SaldoContable_MesAct { get; set; }
        public double co_SaldoBanco_EstCta { get; set; }
        public int co_Cant_Cheque { get; set; }
        public int co_Cant_Deposito { get; set; }
        public int co_Cant_NC { get; set; }
        public int co_Cant_ND { get; set; }
        public double co_TotalCheque { get; set; }
        public double co_TotalDepositos { get; set; }
        public double co_totalNC { get; set; }
        public double co_TotalND { get; set; }
        public string Estado { get; set; }
        public string IdUsuario { get; set; }
        public string IdUsuario_Anu { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string ip { get; set; }
        public string nom_pc { get; set; }
        public string MotivoAnulacion { get; set; }
        public Nullable<int> co_Cant_OtrosIng { get; set; }
        public Nullable<double> co_TotalOtrosIng { get; set; }
        public Nullable<int> co_Cant_OtrosEgr { get; set; }
        public Nullable<double> co_TotalOtrosEgr { get; set; }
        public string co_Observacion { get; set; }
        public string ba_descripcion { get; set; }
        public string IdCtaCble { get; set; }
        public string Periodo { get; set; }
        public double co_SaldoBanco_anterior { get; set; }
    }
}
