//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwba_notasDebCre_masivo
    {
        public int IdEmpresa { get; set; }
        public decimal IdTransaccion { get; set; }
        public string tm_tipo { get; set; }
        public int tm_IdBanco { get; set; }
        public System.DateTime tm_fecha { get; set; }
        public string tm_observacion { get; set; }
        public string tm_IdUsuario { get; set; }
        public double cb_Valor { get; set; }
        public string cb_Observacion { get; set; }
        public System.DateTime cb_Fecha { get; set; }
        public decimal cb_IdCbteCble { get; set; }
        public int cb_IdTipoCte { get; set; }
        public int IdTipoNota { get; set; }
        public string tn_descripcion { get; set; }
        public string tn_tipo { get; set; }
        public string tn_IdCtaCble { get; set; }
        public string tn_IdCentroCosto { get; set; }
    }
}
