//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwba_Conciliacion_det_no_conciliado
    {
        public int IdEmpresa { get; set; }
        public decimal IdCbteCble { get; set; }
        public int IdTipoCbte { get; set; }
        public string CodTipoCbte { get; set; }
        public string tc_TipoCbte { get; set; }
        public string CodTipoCbteBan { get; set; }
        public string Descripcion { get; set; }
        public int IdPeriodo { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public System.DateTime cb_Fecha { get; set; }
        public string cb_Observacion { get; set; }
        public string cb_Cheque { get; set; }
        public Nullable<System.DateTime> cb_FechaCheque { get; set; }
        public string ba_descripcion { get; set; }
        public string IdCtaCble { get; set; }
        public string pc_Cuenta { get; set; }
        public double dc_Valor { get; set; }
        public string Estado { get; set; }
        public int SecuenciaCbteCble { get; set; }
        public string ReferenciaCbte { get; set; }
        public decimal IdConciliacion { get; set; }
        public int SecuenciaConciliacion { get; set; }
        public string tipo_IngEgr { get; set; }
        public string No_Conciliado { get; set; }
    }
}
