//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcaj_MovCaja_x_Cobro_Anticipo
    {
        public int IdEmpresa { get; set; }
        public decimal IdCbteCble { get; set; }
        public int IdTipocbte { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public int IdCaja { get; set; }
        public string IdCtaCble_TipoCobro { get; set; }
        public string IdCtaCble_ban { get; set; }
        public decimal IdCobro { get; set; }
        public string IdCobro_tipo { get; set; }
        public double cr_TotalCobro { get; set; }
        public Nullable<int> Documento_Cobrado { get; set; }
        public string nCliente { get; set; }
        public string nSucursal { get; set; }
        public int IdPeriodo_Caja { get; set; }
        public System.DateTime cr_fecha { get; set; }
        public System.DateTime cr_fechaDocu { get; set; }
        public string cr_NumDocumento { get; set; }
        public double Expr1 { get; set; }
        public double cm_valor { get; set; }
    }
}
