//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcaj_caj_Caja_Movimiento
    {
        public int IdEmpresa { get; set; }
        public decimal IdCbteCble { get; set; }
        public int IdTipocbte { get; set; }
        public string cm_Signo { get; set; }
        public string cm_beneficiario { get; set; }
        public double cm_valor { get; set; }
        public int IdTipoMovi { get; set; }
        public string cm_observacion { get; set; }
        public int IdCaja { get; set; }
        public int IdPeriodo { get; set; }
        public System.DateTime cm_fecha { get; set; }
        public string IdUsuario { get; set; }
        public string IdUsuario_Anu { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public System.DateTime Fecha_Transac { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public string Estado { get; set; }
        public string MotivoAnulacion { get; set; }
        public string IdUsuario_Aprueba { get; set; }
        public string NTipoMov { get; set; }
        public Nullable<decimal> IdCbteCble_Anu { get; set; }
        public Nullable<int> IdTipocbte_Anu { get; set; }
        public string CodMoviCaja { get; set; }
        public string ca_Descripcion { get; set; }
        public string ResponsableCaja { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public string Su_Descripcion { get; set; }
        public Nullable<decimal> IdTipoFlujo { get; set; }
        public string nom_tipoFlujo { get; set; }
        public string IdTipo_Persona { get; set; }
        public Nullable<decimal> IdEntidad { get; set; }
        public string nom_Beneficiario { get; set; }
        public Nullable<decimal> IdPersona { get; set; }
        public Nullable<int> IdPuntoVta { get; set; }
        public Nullable<decimal> IdRecibo { get; set; }
    }
}
