//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcp_retencion
    {
        public int IdEmpresa { get; set; }
        public decimal IdRetencion { get; set; }
        public Nullable<int> IdEmpresa_Ogiro { get; set; }
        public Nullable<decimal> IdCbte_CXP { get; set; }
        public Nullable<int> IdTipoCbte_Ogiro { get; set; }
        public string Factura_Prov { get; set; }
        public Nullable<System.DateTime> co_FechaFactura { get; set; }
        public string NumeroRT { get; set; }
        public System.DateTime Fecha_RT { get; set; }
        public string AutorizacionRT { get; set; }
        public string EstadoRT { get; set; }
        public string ImpresaRT { get; set; }
        public string observacionRT { get; set; }
        public string re_Tiene_RTiva { get; set; }
        public string re_Tiene_RFuente { get; set; }
        public Nullable<decimal> IdProveedor { get; set; }
        public string Nombre_Prov { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Total_Retencion { get; set; }
        public string serie { get; set; }
        public string NumRetencion { get; set; }
        public string IdUsuario { get; set; }
        public System.DateTime Fecha_Transac { get; set; }
        public Nullable<System.DateTime> Fecha_Autorizacion { get; set; }
    }
}
