//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcp_retencion_x_RET_IVA
    {
        public int IdEmpresa { get; set; }
        public decimal IdRetencion { get; set; }
        public string serie { get; set; }
        public string NumRetencion { get; set; }
        public string NAutorizacion { get; set; }
        public string re_tipoRet_RIVA { get; set; }
        public Nullable<double> re_baseRetencion_RIVA { get; set; }
        public Nullable<double> re_Porcen_retencion_RIVA { get; set; }
        public Nullable<double> re_valor_retencion_RIVA { get; set; }
        public Nullable<int> IdEmpresa_Ogiro { get; set; }
        public Nullable<decimal> IdCbteCble_Ogiro { get; set; }
        public Nullable<int> IdTipoCbte_Ogiro { get; set; }
    }
}
