//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcp_Retenciones_x_tipo_impresion
    {
        public int IdEmpresa { get; set; }
        public string Sucursal { get; set; }
        public decimal IdProveedor { get; set; }
        public string Proveedor { get; set; }
        public decimal NumCbteCXP { get; set; }
        public string NumDocumento { get; set; }
        public System.DateTime co_FechaFactura { get; set; }
        public System.DateTime co_FechaFactura_vct { get; set; }
        public string Referencia { get; set; }
        public double co_total { get; set; }
        public double co_valorpagar { get; set; }
        public string NAutorizacion { get; set; }
        public System.DateTime FechaRT { get; set; }
        public string sImpresion { get; set; }
        public string TipoImpresion { get; set; }
        public int IdTipoCbte_Ogiro { get; set; }
        public decimal IdCbteCble_Ogiro { get; set; }
        public decimal IdRetencion { get; set; }
        public string serie { get; set; }
        public string NumRetencion { get; set; }
    }
}
