//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_cbtecble_Con_Saldo
    {
        public int IdEmpresa { get; set; }
        public int IdTipoCbte { get; set; }
        public decimal IdCbteCble { get; set; }
        public Nullable<double> dc_Valor { get; set; }
        public Nullable<double> MontoOG { get; set; }
        public Nullable<double> SaldoDiario { get; set; }
        public string Detalle { get; set; }
        public string cb_Observacion { get; set; }
        public System.DateTime cb_Fecha { get; set; }
    }
}
