//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwct_plancta_nivel
    {
        public int IdEmpresa { get; set; }
        public int IdNivelCta { get; set; }
        public int nv_NumDigitos { get; set; }
        public string nv_Descripcion { get; set; }
        public string Estado { get; set; }
        public Nullable<int> nv_NumDigitos_total { get; set; }
    }
}
