//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcxc_cobro_x_caj_Caja_Movimiento
    {
        public int cbr_IdEmpresa { get; set; }
        public string em_nombre { get; set; }
        public string Su_Descripcion { get; set; }
        public int cbr_IdSucursal { get; set; }
        public decimal cbr_IdCobro { get; set; }
        public int mcj_IdEmpresa { get; set; }
        public decimal mcj_IdCbteCble { get; set; }
        public int mcj_IdTipocbte { get; set; }
        public string tc_descripcion { get; set; }
        public string tc_TipoCbte { get; set; }
    }
}
