//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcxc_Cobro_x_anticipo_x_cobros
    {
        public int IdEmpresa { get; set; }
        public decimal IdAnticipo { get; set; }
        public int Secuencia { get; set; }
        public string IdCobro_tipo { get; set; }
        public Nullable<int> IdEmpresa_Cobro { get; set; }
        public Nullable<int> IdSucursal_cobro { get; set; }
        public Nullable<decimal> IdCobro_cobro { get; set; }
        public decimal IdCliente { get; set; }
        public System.DateTime cr_fecha { get; set; }
        public System.DateTime cr_fechaDocu { get; set; }
        public System.DateTime cr_fechaCobro { get; set; }
        public string cr_observacion { get; set; }
        public string cr_Banco { get; set; }
        public string cr_cuenta { get; set; }
        public string cr_NumDocumento { get; set; }
        public string cr_Tarjeta { get; set; }
        public string cr_propietarioCta { get; set; }
        public Nullable<int> mcj_IdEmpresa { get; set; }
        public Nullable<decimal> mcj_IdCbteCble { get; set; }
        public Nullable<int> mcj_IdTipocbte { get; set; }
        public double cr_TotalCobro { get; set; }
        public Nullable<int> IdBanco { get; set; }
    }
}
