//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCXC_EstadoCta_x_Cliente
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public string Su_Descripcion { get; set; }
        public decimal IdCliente { get; set; }
        public string vt_tipoDoc { get; set; }
        public string numDocumento { get; set; }
        public decimal IdCbteVta { get; set; }
        public System.DateTime vt_fecha { get; set; }
        public System.DateTime vt_fech_venc { get; set; }
        public decimal vt_plazo { get; set; }
        public Nullable<double> vt_total { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Valor_x_Pagar { get; set; }
        public Nullable<int> Valor_Vencido { get; set; }
        public Nullable<int> Saldo { get; set; }
        public int IdReg { get; set; }
    }
}
