//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcxc_anticipos_x_cruzar
    {
        public Nullable<int> IdEmpresa_Cobro { get; set; }
        public Nullable<int> IdSucursal_cobro { get; set; }
        public Nullable<decimal> IdCobro_cobro { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdAnticipo { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdCliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Observacion { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public string IdCobro_tipo { get; set; }
        public string cr_Banco { get; set; }
        public string cr_NumDocumento { get; set; }
        public int IdCaja { get; set; }
        public double cr_TotalCobro { get; set; }
        public double Saldo_Pendiente { get; set; }
        public string IdCtaCble_cxc { get; set; }
        public string IdCtaCble_Anti { get; set; }
    }
}
