//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_orden_despacho_detalle
    {
        public string pe_nombreCompleto { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public int Secuencia { get; set; }
        public decimal IdProducto { get; set; }
        public double od_Precio { get; set; }
        public double od_cantidad { get; set; }
        public double od_PorDescUnitario { get; set; }
        public double od_DescUnitario { get; set; }
        public double od_PrecioFinal { get; set; }
        public double od_Subtotal { get; set; }
        public double od_iva { get; set; }
        public double od_total { get; set; }
        public double od_costo { get; set; }
        public string od_tieneIVA { get; set; }
        public string od_detallexItems { get; set; }
        public string bo_Descripcion { get; set; }
        public string Su_Descripcion { get; set; }
        public int IdBodega { get; set; }
        public int IdSucursal { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdOrdenDespacho { get; set; }
        public decimal IdCliente { get; set; }
        public int IdVendedor { get; set; }
        public decimal IdTransportista { get; set; }
        public System.DateTime od_fecha { get; set; }
        public int od_plazo { get; set; }
        public System.DateTime od_fech_venc { get; set; }
        public string od_Observacion { get; set; }
        public double od_TotalKilos { get; set; }
        public double od_TotalQuintales { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string Estado { get; set; }
        public string Ve_Vendedor { get; set; }
        public decimal Expr1 { get; set; }
        public string em_nombre { get; set; }
        public string em_telefonos { get; set; }
        public string em_direccion { get; set; }
        public byte[] em_logo { get; set; }
        public string CodOrdenDespacho { get; set; }
        public string od_DespAbierto { get; set; }
    }
}
