//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_liquidaciones_group_x_liqui_x_periodo_x_cliente
    {
        public int IdEmpresa { get; set; }
        public decimal IdLiquidacion { get; set; }
        public int IdPeriodo { get; set; }
        public string cod_liquidacion { get; set; }
        public decimal IdCliente { get; set; }
        public System.DateTime fecha_liqui { get; set; }
        public string Observacion { get; set; }
        public Nullable<double> Subtotal { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<double> total_liquidacion { get; set; }
        public string pe_nombreCompleto { get; set; }
    }
}
