//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_notaCreDeb_sri
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdNota { get; set; }
        public string CreDeb { get; set; }
        public string CodNota { get; set; }
        public string Serie1 { get; set; }
        public string Serie2 { get; set; }
        public decimal IdCliente { get; set; }
        public System.DateTime no_fecha { get; set; }
        public string Estado { get; set; }
        public string NaturalezaNota { get; set; }
        public string NumAutorizacion { get; set; }
        public string RazonSocial { get; set; }
        public string NombreComercial { get; set; }
        public string ContribuyenteEspecial { get; set; }
        public string ObligadoAllevarConta { get; set; }
        public string em_ruc { get; set; }
        public string em_direccion { get; set; }
        public string Su_Descripcion { get; set; }
        public string Su_Direccion { get; set; }
        public string cl_RazonSocial { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string IdTipoDocumento { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string pe_correo { get; set; }
        public string NumNota_Impresa { get; set; }
        public string num_Factura { get; set; }
        public System.DateTime fecha_fact { get; set; }
        public string obser_fact { get; set; }
        public string obser_Nota { get; set; }
        public string nc_Motivo { get; set; }
        public string tipo_doc_aplicado { get; set; }
    }
}
