//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfa_cliente_x_ct_centro_costo
    {
        public string pe_razonSocial { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string pe_direccion { get; set; }
        public string pe_telefonoOfic { get; set; }
        public string pe_telefonoCasa { get; set; }
        public string pe_correo { get; set; }
        public string pe_Naturaleza { get; set; }
        public string pe_estado { get; set; }
        public string IdTipoDocumento { get; set; }
        public decimal IdCliente_cli { get; set; }
        public string IdCentroCosto_cc { get; set; }
        public int IdEmpresa_cc { get; set; }
        public int IdEmpresa_cli { get; set; }
        public string IdActividadComercial { get; set; }
        public string Estado { get; set; }
        public string IdProvincia { get; set; }
        public string IdPais { get; set; }
        public string Descripcion_Ciudad { get; set; }
        public string nom_Centro_costo { get; set; }
        public string nom_Cliente { get; set; }
        public string pe_celular { get; set; }
        public string num_cta_acreditacion { get; set; }
        public string pc_Estado { get; set; }
        public string CodCentroCosto { get; set; }
        public string IdCentroCostoPadre { get; set; }
    }
}
