//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGe_tb_Tarjeta_tb_Parametro
    {
        public int IdTarjeta { get; set; }
        public string tr_Descripcion { get; set; }
        public string Estado { get; set; }
        public int IdBanco { get; set; }
        public int IdEmpresa { get; set; }
        public string IdCtaCble_Comision { get; set; }
        public Nullable<double> Porcetaje_Comision { get; set; }
        public string IdCobro_tipo_x_Tarj { get; set; }
        public string IdCobro_tipo_x_RetFu { get; set; }
        public string IdCobro_tipo_x_RetIva { get; set; }
        public string IdCtaCble_Tarj { get; set; }
    }
}
