//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIMP_Orden_Compra
    {
        public string Codigo { get; set; }
        public decimal C__Orden_Compra { get; set; }
        public string Sucursal { get; set; }
        public string Proveedor { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int IdEmpresa { get; set; }
        public int IdSucusal { get; set; }
        public string Estado { get; set; }
        public Nullable<int> ci_plazo { get; set; }
        public Nullable<System.DateTime> ci_fecha { get; set; }
        public Nullable<decimal> IdProveedor { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<double> ci_costo_Flete_externo { get; set; }
        public Nullable<double> ci_costo_Flete_interno { get; set; }
        public Nullable<double> ci_costoSeguro { get; set; }
        public Nullable<double> ci_costoCif { get; set; }
        public Nullable<double> ci_GastosTotales { get; set; }
        public string IdVia { get; set; }
        public Nullable<System.DateTime> ci_fecha_aprobacion { get; set; }
        public Nullable<System.DateTime> ci_fechaFactProv { get; set; }
        public Nullable<System.DateTime> ci_fechVenciFact { get; set; }
        public Nullable<System.DateTime> ci_fechaDespProv { get; set; }
        public Nullable<System.DateTime> ci_fechaRecEmb { get; set; }
        public Nullable<System.DateTime> ci_fechaAproxSal { get; set; }
        public Nullable<System.DateTime> ci_fec_est_llegada { get; set; }
        public Nullable<System.DateTime> ci_fecha_llegada_Bodega { get; set; }
        public Nullable<System.DateTime> ci_fechaRealArri { get; set; }
        public Nullable<System.DateTime> ci_fechaDocAAA { get; set; }
        public Nullable<System.DateTime> ci_fecha_liquidacion { get; set; }
        public Nullable<System.DateTime> ci_fecha_sal_aduana { get; set; }
        public Nullable<int> ci_diasFecFacProv { get; set; }
        public Nullable<int> ci_diasFecDespProv { get; set; }
        public Nullable<int> ci_diasFecAproxSal { get; set; }
        public Nullable<int> ci_diasFecAproxLleg { get; set; }
        public Nullable<int> ci_diasNaciona { get; set; }
        public Nullable<System.DateTime> ci_fecha_pago { get; set; }
        public Nullable<System.DateTime> ci_fecha_salida { get; set; }
        public Nullable<System.DateTime> ci_fecha_llegada { get; set; }
        public Nullable<System.DateTime> ci_fecha_despacho { get; set; }
        public Nullable<int> ci_dias_estimados { get; set; }
        public Nullable<double> ci_valor_derecho { get; set; }
        public Nullable<int> IdMonedaOrigen { get; set; }
        public Nullable<int> IdMonedaCambiaria { get; set; }
        public Nullable<double> ci_EquivalenciaMoneda { get; set; }
        public string IdCicloImportacion { get; set; }
        public string IdCtaCble_Inven { get; set; }
        public string IdCtaCble_import { get; set; }
        public Nullable<int> IdEmbarcador { get; set; }
        public string ci_contabilizada { get; set; }
        public Nullable<decimal> ci_Idfecha_Bodega { get; set; }
        public Nullable<System.DateTime> ci_fechaRegsis { get; set; }
        public Nullable<System.DateTime> ci_ultFechaModi { get; set; }
        public string ci_ultUserModi { get; set; }
        public string IdPaisOrgCarga { get; set; }
        public string IdPaisProceCarga { get; set; }
        public string ci_dui { get; set; }
        public Nullable<System.DateTime> ci_fechaHoraAnul { get; set; }
        public string ci_userAnul { get; set; }
        public Nullable<int> ci_anio { get; set; }
        public Nullable<int> ci_mes { get; set; }
        public Nullable<System.DateTime> ci_FechaCosteo { get; set; }
        public string IdUsuarioUltMod { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdUsuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
        public string MotiAnula { get; set; }
        public Nullable<double> ci_tonelaje { get; set; }
        public string ci_lugarEmbarque { get; set; }
        public string Buque { get; set; }
        public string Naviera { get; set; }
        public Nullable<double> CFR { get; set; }
        public string IdCategoria { get; set; }
        public Nullable<double> ci_Total { get; set; }
        public string IdEstadoLiquidacion { get; set; }
        public string NumFacturaProvedor { get; set; }
        public Nullable<int> ci_diasEmbarque { get; set; }
        public Nullable<System.DateTime> ci_fechaFirmaContrato { get; set; }
        public string Tipo_Importacion { get; set; }
        public Nullable<System.DateTime> Fecha_Maximo_Despacho { get; set; }
    }
}
