//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_Movi_Inven_x_CodBarra_CusCider
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public int IdMovi_inven_tipo { get; set; }
        public decimal IdNumMovi { get; set; }
        public string CodMoviInven { get; set; }
        public string cm_tipo { get; set; }
        public string cm_observacion { get; set; }
        public System.DateTime cm_fecha { get; set; }
        public decimal IdProducto { get; set; }
        public double dm_cantidad { get; set; }
        public double dm_stock_ante { get; set; }
        public double dm_stock_actu { get; set; }
        public int dm_precio { get; set; }
        public double mv_costo { get; set; }
        public Nullable<double> dm_cantidadCodBarra { get; set; }
        public string dm_observacion { get; set; }
        public Nullable<int> et_IdEmpresa { get; set; }
        public Nullable<int> et_IdProcesoProductivo { get; set; }
        public Nullable<int> et_IdEtapa { get; set; }
        public Nullable<int> ot_IdEmpresa { get; set; }
        public Nullable<int> ot_IdSucursal { get; set; }
        public string ot_CodObra { get; set; }
        public Nullable<decimal> ot_IdOrdenTaller { get; set; }
        public string CodigoBarra { get; set; }
        public string Expr1 { get; set; }
        public string pr_observacion { get; set; }
        public string pr_descripcion { get; set; }
    }
}
