//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_Ingreso_x_OrdenCompra
    {
        public int IdEmpresa { get; set; }
        public decimal IdIngreso_x_oc { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public string codigo { get; set; }
        public string Referencia { get; set; }
        public System.DateTime Fecha_ing_bod { get; set; }
        public decimal IdProveedor { get; set; }
        public int IdMotivo { get; set; }
        public string Observacion { get; set; }
        public string Tipo_local_ext { get; set; }
        public Nullable<int> IdEmpresa_mIinv { get; set; }
        public Nullable<int> IdSucursal_mInv { get; set; }
        public Nullable<int> IdBodega_mInv { get; set; }
        public Nullable<int> IdMovi_inven_tipo_mInv { get; set; }
        public Nullable<decimal> IdNumMovi_mInv { get; set; }
        public string Estado { get; set; }
        public string nom_bodega { get; set; }
        public string nom_sucursal { get; set; }
        public string nom_proveedor { get; set; }
        public string nom_motivo { get; set; }
        public string tm_descripcion { get; set; }
    }
}
