//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_Zona_vs_ct_Centro_Costo
    {
        public decimal IdCentroCosto { get; set; }
        public string Centro_costo { get; set; }
        public string IdZona { get; set; }
        public string Zona { get; set; }
        public string IdSubZona { get; set; }
        public string Subzona { get; set; }
        public string CodigoZN { get; set; }
        public string IdCtaCbleZona { get; set; }
    }
}
