//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_Orden_servicio_x_activo_fijo
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdOrdenSer_x_Af { get; set; }
        public int IdBodega { get; set; }
        public int IdActivoFijo { get; set; }
        public decimal IdProveedor { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Num_Fact { get; set; }
        public string Num_Documento { get; set; }
        public string IdCentroCosto { get; set; }
        public string Observacion { get; set; }
        public string Estado { get; set; }
        public string bo_Descripcion { get; set; }
        public string Af_Nombre { get; set; }
        public string Centro_costo { get; set; }
        public string pr_nombre { get; set; }
        public string Su_Descripcion { get; set; }
    }
}
