//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_Ingreso_x_OrdenCompra_det
    {
        public int IdEmpresa { get; set; }
        public decimal IdIngreso_x_oc { get; set; }
        public int Secuencia { get; set; }
        public decimal IdProducto { get; set; }
        public double Cant { get; set; }
        public double Cant_a_recibir { get; set; }
        public double Cant_recibida { get; set; }
        public Nullable<int> IdEmpresa_oc { get; set; }
        public Nullable<int> IdSucursal_oc { get; set; }
        public Nullable<decimal> IdOrdenCompra { get; set; }
        public Nullable<int> Secuencia_oc { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
        public Nullable<int> IdPunto_cargo { get; set; }
        public string nom_sucursal { get; set; }
        public string nom_producto { get; set; }
        public string IdUnidadMedida { get; set; }
    }
}
