//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_movi_inve
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public int IdMovi_inven_tipo { get; set; }
        public decimal IdNumMovi { get; set; }
        public string cm_tipo { get; set; }
        public string cm_observacion { get; set; }
        public System.DateTime cm_fecha { get; set; }
        public Nullable<int> IdCbteCble_Tipo { get; set; }
        public Nullable<decimal> IdCbteCble { get; set; }
        public string IdCtaCble { get; set; }
        public int cm_anio { get; set; }
        public int cm_mes { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string IdUsuarioUltModi { get; set; }
        public Nullable<System.DateTime> Fecha_UltMod { get; set; }
        public string IdusuarioUltAnu { get; set; }
        public Nullable<System.DateTime> Fecha_UltAnu { get; set; }
        public string nom_pc { get; set; }
        public string ip { get; set; }
        public string Estado { get; set; }
        public string NomSucursal { get; set; }
        public string NomBodega { get; set; }
        public string CodTipoMovi { get; set; }
        public string NomTipoMovi { get; set; }
        public string NemoTipoMovi { get; set; }
        public string CodMoviInven { get; set; }
        public string IdCentroCosto { get; set; }
        public string CodCentroCosto { get; set; }
        public string Centro_costo { get; set; }
        public Nullable<decimal> IdProvedor { get; set; }
        public string NumDocumentoRelacionado { get; set; }
        public string NumFactura { get; set; }
        public Nullable<int> IdEmpresa_x_Anu { get; set; }
        public Nullable<int> IdSucursal_x_Anu { get; set; }
        public Nullable<int> IdBodega_x_Anu { get; set; }
        public Nullable<int> IdMovi_inven_tipo_x_Anu { get; set; }
        public Nullable<decimal> IdNumMovi_x_Anu { get; set; }
        public string MotivoAnulacion { get; set; }
        public Nullable<int> IdMotivo_Inv { get; set; }
    }
}
