//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_movi_inve_detalle
    {
        public long IdRow { get; set; }
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public int IdMovi_inven_tipo { get; set; }
        public decimal IdNumMovi { get; set; }
        public int Secuencia { get; set; }
        public string mv_tipo_movi { get; set; }
        public decimal IdProducto { get; set; }
        public double dm_cantidad { get; set; }
        public double dm_stock_ante { get; set; }
        public double dm_stock_actu { get; set; }
        public string dm_observacion { get; set; }
        public double mv_costo { get; set; }
        public string Su_Descripcion { get; set; }
        public string bo_Descripcion { get; set; }
        public string pr_codigo { get; set; }
        public string pr_descripcion { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public string Descripcion { get; set; }
        public string IdCategoria { get; set; }
        public string ca_Categoria { get; set; }
        public string RutaPadre { get; set; }
        public string cm_observacion { get; set; }
        public Nullable<System.DateTime> cm_fecha { get; set; }
        public string CodMoviInven { get; set; }
        public string CodTipoMoviInven { get; set; }
        public string TipoMoviInvent { get; set; }
        public Nullable<int> IdPunto_cargo { get; set; }
        public Nullable<int> IdPunto_cargo_grupo { get; set; }
        public Nullable<int> IdMotivo_Inv { get; set; }
        public Nullable<int> IdEmpresa_ing_egr { get; set; }
        public Nullable<int> IdSucursal_ing_egr { get; set; }
        public Nullable<int> IdMovi_inven_tipo_ing_egr { get; set; }
        public Nullable<decimal> IdNumMovi_ing_egr { get; set; }
        public Nullable<int> Secuencia_ing_egr { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
        public string IdUnidadMedida { get; set; }
        public double dm_cantidad_sinConversion { get; set; }
        public string IdUnidadMedida_sinConversion { get; set; }
        public Nullable<double> mv_costo_sinConversion { get; set; }
        public string nom_punto_cargo { get; set; }
    }
}
