//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_subgrupo_x_CentroCosto_x_SubCentroCosto_x_CtaCble_no_parametrizados
    {
        public long IdRow { get; set; }
        public int IdEmpresa { get; set; }
        public string IdCategoria { get; set; }
        public string ca_Categoria { get; set; }
        public int IdLinea { get; set; }
        public string nom_linea { get; set; }
        public int IdGrupo { get; set; }
        public string nom_grupo { get; set; }
        public int IdSubGrupo { get; set; }
        public string nom_subgrupo { get; set; }
        public string IdCentroCosto { get; set; }
        public string nom_Centro { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
        public string nom_Subcentro { get; set; }
    }
}
