//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwin_Guia_x_traspaso_bodega_x_ordencompra_local_det
    {
        public int IdEmpresa { get; set; }
        public decimal IdGuia { get; set; }
        public decimal IdProducto { get; set; }
        public int secuencia { get; set; }
        public Nullable<int> IdEmpresa_OC { get; set; }
        public Nullable<int> IdSucursal_OC { get; set; }
        public Nullable<decimal> IdOrdenCompra_OC { get; set; }
        public Nullable<int> Secuencia_OC { get; set; }
        public string observacion { get; set; }
        public Nullable<double> Cantidad_enviar { get; set; }
        public double do_Cantidad { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
        public Nullable<int> IdPunto_cargo { get; set; }
        public string IdUnidadMedida { get; set; }
        public double do_precioCompra { get; set; }
        public Nullable<int> IdPunto_cargo_grupo { get; set; }
        public string pr_codigo { get; set; }
        public string Referencia { get; set; }
        public string cod_producto { get; set; }
        public string nom_producto { get; set; }
        public string obs_OCompra { get; set; }
        public decimal IdOrdenCompra { get; set; }
    }
}
