//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwpre_presupuesto_plancta
    {
        public Nullable<decimal> IdPresupuesto { get; set; }
        public string IdAnio { get; set; }
        public string IdCtaCble { get; set; }
        public Nullable<int> Secuencia { get; set; }
        public string CodigoPresupuesto { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdTipoRubro { get; set; }
        public string CodRubro { get; set; }
        public string NombreRubro { get; set; }
        public Nullable<double> Enero { get; set; }
        public Nullable<double> febrero { get; set; }
        public Nullable<double> Marzo { get; set; }
        public Nullable<double> Abril { get; set; }
        public Nullable<double> Mayo { get; set; }
        public Nullable<double> Junio { get; set; }
        public Nullable<double> Julio { get; set; }
        public Nullable<double> Agosto { get; set; }
        public Nullable<double> Septiembre { get; set; }
        public Nullable<double> Octubre { get; set; }
        public Nullable<double> Noviembre { get; set; }
        public Nullable<double> Diciembre { get; set; }
        public Nullable<double> Total { get; set; }
        public int IdEmpresa { get; set; }
    }
}
