//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwprd_OrdenCompraCidersus
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdOrdenCompra { get; set; }
        public decimal IdProveedor { get; set; }
        public decimal IdProducto { get; set; }
        public string em_nombre { get; set; }
        public string pr_nombre { get; set; }
        public int oc_plazo { get; set; }
        public System.DateTime oc_fecha { get; set; }
        public string pr_codigo { get; set; }
        public double do_Cantidad { get; set; }
        public string IdUnidadMedida { get; set; }
        public string pr_descripcion { get; set; }
        public double do_precioCompra { get; set; }
        public double do_subtotal { get; set; }
        public double do_iva { get; set; }
        public double do_total { get; set; }
        public double do_descuento { get; set; }
        public double do_porc_des { get; set; }
        public string pr_contribuyenteEspecial { get; set; }
        public string oc_NumDocumento { get; set; }
        public string Usuario_Aprueba { get; set; }
        public string Usuario_Solicitante { get; set; }
        public string TerminoPago { get; set; }
        public int DiasTerminoPago { get; set; }
        public string UnidadMedidaConsumo { get; set; }
    }
}
