//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwprd_ProcesoProductivo
    {
        public string pp_Estado { get; set; }
        public int IdEmpresa_Pr { get; set; }
        public int IdProcesoProductivo { get; set; }
        public string CodObra { get; set; }
        public string ob_descripcion { get; set; }
        public string Nombre { get; set; }
        public System.DateTime Fecha { get; set; }
        public string ob_Estado { get; set; }
    }
}
