//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwprd_Ensamblado_CabDet_CusCider
    {
        public int IdBodega { get; set; }
        public decimal IdGrupoTrabajo { get; set; }
        public decimal cab_IdProducto { get; set; }
        public string CBMaestro { get; set; }
        public string CodObra { get; set; }
        public decimal IdOrdenTaller { get; set; }
        public string IdUsuario { get; set; }
        public string IdUsuarioAnu { get; set; }
        public string MotivoAnu { get; set; }
        public string IdUsuarioUltModi { get; set; }
        public Nullable<System.DateTime> FechaAnu { get; set; }
        public System.DateTime FechaTransac { get; set; }
        public Nullable<System.DateTime> FechaUltModi { get; set; }
        public string cab_Estado { get; set; }
        public string cab_observacion { get; set; }
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdEnsamblado { get; set; }
        public int Secuencia { get; set; }
        public decimal det_IdProducto { get; set; }
        public string CodigoBarra { get; set; }
        public string det_observacion { get; set; }
        public int en_cantidad { get; set; }
    }
}
