//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwpre_PedidoXPresupuesto
    {
        public int IdEmpresa { get; set; }
        public decimal IdPedidoXPre { get; set; }
        public string Departamento { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observacion { get; set; }
        public string Proveedor1 { get; set; }
        public string Proveedor2 { get; set; }
        public string Proveedor3 { get; set; }
        public string IdUsuario { get; set; }
        public string Estado { get; set; }
        public string MotivoAnulacion { get; set; }
    }
}
