//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwprd_GrupoTrabajo_x_Etapa
    {
        public string NombreEtapa { get; set; }
        public string gt_descripcion { get; set; }
        public decimal IdGrupoTrabajo { get; set; }
        public int IdSucursal { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdLider { get; set; }
        public int IdEtapa { get; set; }
        public string CodObra { get; set; }
    }
}
