//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRo_Acta_Finiquito_X_Empleado
    {
        public int IdEmpresa { get; set; }
        public decimal IdActaFiniquito { get; set; }
        public decimal IdEmpleado { get; set; }
        public string IdCausaTerminacion { get; set; }
        public Nullable<decimal> IdContrato { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public double UltimaRemuneracion { get; set; }
        public string Observacion { get; set; }
        public double Ingresos { get; set; }
        public double Egresos { get; set; }
        public Nullable<bool> EsMujerEmbarazada { get; set; }
        public Nullable<bool> EsDirigenteSindical { get; set; }
        public Nullable<bool> EsPorDiscapacidad { get; set; }
        public Nullable<bool> EsPorEnfermedadNoProfesional { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string NomCompleto { get; set; }
        public int IdSecuencia { get; set; }
        public string Expr1 { get; set; }
        public string Signo { get; set; }
        public double Valor { get; set; }
    }
}
