//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRo_Conf_Rubros_Acumulados
    {
        public int IdEmpresa { get; set; }
        public string IdRubro { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Configurable { get; set; }
        public Nullable<System.DateTime> Fec_Inicio_Acumulacion { get; set; }
        public Nullable<System.DateTime> Fec_Fin_Acumulacion { get; set; }
        public decimal IdEmpleado { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
    }
}
