//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRo_Conf_Rubros
    {
        public int IdEmpresa { get; set; }
        public string IdRubro { get; set; }
        public int OrdenPres { get; set; }
        public string Estado { get; set; }
        public string ru_tipo { get; set; }
        public string ru_descripcion { get; set; }
        public string NombreCorto { get; set; }
    }
}
