//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_Asignacion_Implemento_x_Empleado
    {
        public int IdEmpresa { get; set; }
        public decimal IdAsignacion_Impl { get; set; }
        public string Tipo_Movimiento { get; set; }
        public System.DateTime Fecha_Entrega { get; set; }
        public decimal IdEmpleado { get; set; }
        public string Observacion { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Transac { get; set; }
        public string pe_nombreCompleto { get; set; }
    }
}
