//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRo_Config_rubros_x_Prestamo
    {
        public int IdEmpresa { get; set; }
        public Nullable<int> orden_prest { get; set; }
        public string IdRubro_prest { get; set; }
        public string rub_codigo_prest { get; set; }
        public string ru_descripcion_prest { get; set; }
        public string NombreCorto_prest { get; set; }
        public string ru_tipo_prest { get; set; }
        public string ru_estado_prest { get; set; }
    }
}
