//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_historicoSueldovsEmpl
    {
        public string pe_nombreCompleto { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public string pe_cedulaRuc { get; set; }
        public int Secuencia { get; set; }
        public double SueldoAnterior { get; set; }
        public double SueldoActual { get; set; }
        public double PorIncrementoSueldo { get; set; }
        public double ValorIncrementoSueldo { get; set; }
        public string Motivo { get; set; }
        public System.DateTime Fecha { get; set; }
        public string de_descripcion { get; set; }
        public string ca_descripcion { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdEmpleado { get; set; }
    }
}
