//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_marcaciones_Equipo_x_TipoMarcacion
    {
        public int IdEquipoMar { get; set; }
        public string IdTipoMarcaciones_sys { get; set; }
        public string IdTipoMarcaciones_Biometrico { get; set; }
    }
}
