//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_empleados
    {
        public string pe_nombreCompleto { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string CodPersona { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdEmpleado { get; set; }
        public Nullable<decimal> IdEmpleado_Supervisor { get; set; }
        public decimal IdPersona { get; set; }
        public int IdSucursal { get; set; }
        public string em_codigo { get; set; }
        public string em_lugarNacimiento { get; set; }
        public string em_CarnetIees { get; set; }
        public string em_cedulaMil { get; set; }
        public string IdTipoEmpleado { get; set; }
        public Nullable<System.DateTime> em_fecha_ingreso { get; set; }
        public Nullable<System.DateTime> em_fechaSalida { get; set; }
        public Nullable<System.DateTime> em_fechaTerminoContra { get; set; }
        public Nullable<System.DateTime> em_fechaIngaRol { get; set; }
        public string IdTipoSangre { get; set; }
        public string em_SeAcreditaBanco { get; set; }
        public string em_tipoCta { get; set; }
        public string em_NumCta { get; set; }
        public string em_SepagaBeneficios { get; set; }
        public string em_SePagaConTablaSec { get; set; }
        public string em_estado { get; set; }
        public double em_sueldoBasicoMen { get; set; }
        public Nullable<double> em_SueldoExtraMen { get; set; }
        public double em_MovilizacionQuincenal { get; set; }
        public Nullable<int> IdCodSectorial { get; set; }
        public int IdDepartamento { get; set; }
        public Nullable<int> IdCargo { get; set; }
        public byte[] em_foto { get; set; }
        public string em_empEspecial { get; set; }
        public string em_pagoFdoRsv { get; set; }
        public string em_huella { get; set; }
        public string IdCtaCble_Emplea { get; set; }
        public string IdUbicacion { get; set; }
        public byte[] Archivo { get; set; }
        public string NombreArchivo { get; set; }
        public string Codigo_Biometrico { get; set; }
        public Nullable<int> IdArea { get; set; }
        public Nullable<int> IdDivision { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
    }
}
