//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRo_Archivos_Bancos_Generacion_det
    {
        public decimal IdEmpleado { get; set; }
        public string CedulaRuc { get; set; }
        public string NombreCompleto { get; set; }
        public string IdRubro { get; set; }
        public string Tag { get; set; }
        public string DescRubroLargo { get; set; }
        public string DescNombreRubroCorto { get; set; }
        public int Orden { get; set; }
        public double Valor { get; set; }
        public string NominaLiqui { get; set; }
        public string Nomina { get; set; }
        public string Empresa { get; set; }
        public int IdEmpresa { get; set; }
        public string Departamento { get; set; }
        public int IdNominaTipo { get; set; }
        public int IdNominaTipoLiqui { get; set; }
        public System.DateTime FechaIngresa { get; set; }
        public Nullable<bool> rub_visible_reporte { get; set; }
        public string Observacion { get; set; }
        public string TipoMovimiento { get; set; }
        public string EstadoRol { get; set; }
        public string IdCentroCosto { get; set; }
        public int IdPeriodo { get; set; }
        public Nullable<int> pe_anio { get; set; }
        public Nullable<int> pe_mes { get; set; }
        public System.DateTime FechaIni { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Cerrado { get; set; }
        public string Procesado { get; set; }
        public string Contabilizado { get; set; }
        public string TipoCuenta { get; set; }
        public string NumCuenta { get; set; }
        public string IdBanco { get; set; }
        public string TipoIdentificacion { get; set; }
        public Nullable<int> IdDivision { get; set; }
        public string DivisionDescripcion { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public string CodigoLegal { get; set; }
        public int IdDepartamento { get; set; }
        public string ba_descripcion { get; set; }
        public double ValorCancelado { get; set; }
        public double PendientePago { get; set; }
        public decimal IdArchivo { get; set; }
    }
}
