//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRo_Cargo_Empleado_X_Periodo
    {
        public int Id_Empresa { get; set; }
        public decimal Id_Empleado { get; set; }
        public int Id_Periodo { get; set; }
        public string cargo { get; set; }
        public string departamento { get; set; }
        public int IdEmpresa { get; set; }
        public decimal IdEmpleado { get; set; }
        public Nullable<decimal> IdEmpleado_Supervisor { get; set; }
        public decimal IdPersona { get; set; }
        public string IdTipoEmpleado { get; set; }
        public string em_codigo { get; set; }
        public string em_lugarNacimiento { get; set; }
        public string em_CarnetIees { get; set; }
        public string em_cedulaMil { get; set; }
        public Nullable<System.DateTime> em_fecha_ingreso { get; set; }
        public Nullable<System.DateTime> em_fechaSalida { get; set; }
        public Nullable<System.DateTime> em_fechaTerminoContra { get; set; }
        public Nullable<System.DateTime> em_fechaIngaRol { get; set; }
        public string em_SeAcreditaBanco { get; set; }
        public string em_tipoCta { get; set; }
        public string em_NumCta { get; set; }
        public string em_SepagaBeneficios { get; set; }
        public string em_SePagaConTablaSec { get; set; }
        public string em_estado { get; set; }
        public double em_sueldoBasicoMen { get; set; }
        public Nullable<double> em_SueldoExtraMen { get; set; }
        public Nullable<double> em_MovilizacionQuincenal { get; set; }
        public byte[] em_foto { get; set; }
        public string em_empEspecial { get; set; }
        public string em_pagoFdoRsv { get; set; }
        public string em_huella { get; set; }
        public Nullable<int> IdCodSectorial { get; set; }
        public int IdDepartamento { get; set; }
        public string IdTipoSangre { get; set; }
        public Nullable<int> IdCargo { get; set; }
        public string IdCtaCble_Emplea { get; set; }
        public string IdUbicacion { get; set; }
        public string em_mail { get; set; }
        public string CodPersona { get; set; }
        public string pe_Naturaleza { get; set; }
        public string NomCompleto { get; set; }
        public string pe_razonSocial { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public int IdTipoPersona { get; set; }
        public string IdTipoDocumento { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string pe_direccion { get; set; }
        public string pe_telefonoCasa { get; set; }
        public string pe_telefonoOfic { get; set; }
        public string pe_telefonoInter { get; set; }
        public string pe_telfono_Contacto { get; set; }
        public string pe_celular { get; set; }
        public string pe_correo { get; set; }
        public string pe_fax { get; set; }
        public string pe_casilla { get; set; }
        public string pe_sexo { get; set; }
        public string IdEstadoCivil { get; set; }
        public Nullable<System.DateTime> pe_fechaNacimiento { get; set; }
        public string pe_estado { get; set; }
        public Nullable<System.DateTime> pe_fechaCreacion { get; set; }
        public Nullable<System.DateTime> pe_fechaModificacion { get; set; }
        public string Sucursal { get; set; }
        public int IdSucursal { get; set; }
        public string IdTipoLicencia { get; set; }
        public string IdCentroCosto { get; set; }
        public string IdBanco { get; set; }
        public byte[] Archivo { get; set; }
        public string NombreArchivo { get; set; }
        public string Codigo_Biometrico { get; set; }
        public Nullable<int> IdArea { get; set; }
        public Nullable<int> IdDivision { get; set; }
        public string IdCentroCosto_sub_centro_costo { get; set; }
        public double por_discapacidad { get; set; }
        public string carnet_conadis { get; set; }
        public string recibi_uniforme { get; set; }
        public double talla_pant { get; set; }
        public string talla_camisa { get; set; }
        public double talla_zapato { get; set; }
    }
}
