//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_ro_fectividad_Entrega_x_planificacion_x_ruta_x_empleado
    {
        public int IdEmpresa { get; set; }
        public int IdNomina_Tipo { get; set; }
        public int IdPeriodo { get; set; }
        public int IdEmpleado { get; set; }
        public int IdRuta { get; set; }
        public int IdEfectividad { get; set; }
        public double Efectividad_Entrega { get; set; }
        public double Efectividad_Entrega_aplica { get; set; }
        public double Efectividad_Volumen { get; set; }
        public double Efectividad_Volumen_aplica { get; set; }
        public double Recuperacion_cartera { get; set; }
        public Nullable<int> IdZona { get; set; }
        public double Recuperacion_cartera_aplica { get; set; }
    }
}
