//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwro_descuento_no_planificados
    {
        public int IdEmpresa { get; set; }
        public int IdNomina_Tipo { get; set; }
        public decimal IdEmpleado { get; set; }
        public int IdDescuento { get; set; }
        public Nullable<decimal> IdNovedad { get; set; }
        public string IdRubro { get; set; }
        public string Observacion { get; set; }
        public double Valor { get; set; }
        public System.DateTime Fecha_Incidente { get; set; }
        public bool Estado { get; set; }
        public string ru_descripcion { get; set; }
        public string pe_apellido { get; set; }
        public string pe_nombre { get; set; }
        public string pe_razonSocial { get; set; }
        public string pe_nombreCompleto { get; set; }
        public string pe_cedulaRuc { get; set; }
        public Nullable<System.DateTime> Fecha_Transaccion { get; set; }
    }
}
