//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwtb_sis_Documento_Tipo_x_Disenio_Report
    {
        public int IdEmpresa { get; set; }
        public string codDocumentoTipo { get; set; }
        public string descripcion { get; set; }
        public byte[] File_Disenio_Reporte { get; set; }
        public string ApareceCombo_FileReporte { get; set; }
    }
}
