//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntitiesRolesRptGeneral : DbContext
    {
        public EntitiesRolesRptGeneral()
            : base("name=EntitiesRolesRptGeneral")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwROL_Rpt001> vwROL_Rpt001 { get; set; }
        public DbSet<vwROL_Rpt002> vwROL_Rpt002 { get; set; }
        public DbSet<vwROL_Rpt003> vwROL_Rpt003 { get; set; }
        public DbSet<vwROL_Rpt004> vwROL_Rpt004 { get; set; }
        public DbSet<vwROL_Rpt008> vwROL_Rpt008 { get; set; }
        public DbSet<vwROL_Rpt009> vwROL_Rpt009 { get; set; }
        public DbSet<vwROL_Rpt010> vwROL_Rpt010 { get; set; }
        public DbSet<vwROL_Rpt011> vwROL_Rpt011 { get; set; }
        public DbSet<vwROL_Rpt014> vwROL_Rpt014 { get; set; }
        public DbSet<vwROL_Rpt015> vwROL_Rpt015 { get; set; }
        public DbSet<vwROL_Rpt017> vwROL_Rpt017 { get; set; }
        public DbSet<vwROL_Rpt018> vwROL_Rpt018 { get; set; }
        public DbSet<vwROL_Rpt019> vwROL_Rpt019 { get; set; }
        public DbSet<vwROL_Rpt021> vwROL_Rpt021 { get; set; }
        public DbSet<vwROL_Rpt022> vwROL_Rpt022 { get; set; }
        public DbSet<vwROL_Rpt023> vwROL_Rpt023 { get; set; }
        public DbSet<vwROL_Rpt024> vwROL_Rpt024 { get; set; }
        public DbSet<vwROL_Rpt025> vwROL_Rpt025 { get; set; }
        public DbSet<vwROL_Rpt006> vwROL_Rpt006 { get; set; }
        public DbSet<vwROL_Rpt005> vwROL_Rpt005 { get; set; }
        public DbSet<vwROL_Rpt013> vwROL_Rpt013 { get; set; }
        public DbSet<vwROL_Rpt007> vwROL_Rpt007 { get; set; }
    
        public virtual ObjectResult<spROL_Rpt016_Result> spROL_Rpt016(Nullable<int> idempresa, Nullable<int> idnomina, Nullable<System.DateTime> fecha_inicio, Nullable<System.DateTime> fecha_fin)
        {
            var idempresaParameter = idempresa.HasValue ?
                new ObjectParameter("idempresa", idempresa) :
                new ObjectParameter("idempresa", typeof(int));
    
            var idnominaParameter = idnomina.HasValue ?
                new ObjectParameter("idnomina", idnomina) :
                new ObjectParameter("idnomina", typeof(int));
    
            var fecha_inicioParameter = fecha_inicio.HasValue ?
                new ObjectParameter("fecha_inicio", fecha_inicio) :
                new ObjectParameter("fecha_inicio", typeof(System.DateTime));
    
            var fecha_finParameter = fecha_fin.HasValue ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spROL_Rpt016_Result>("spROL_Rpt016", idempresaParameter, idnominaParameter, fecha_inicioParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<spROL_Rpt020_Result> spROL_Rpt020(Nullable<int> idempresa, Nullable<int> idnomina_tipo, Nullable<int> idRubro_25, Nullable<int> idRubro_50, Nullable<int> idRubro_100, Nullable<System.DateTime> fecha_inicio, Nullable<System.DateTime> fecha_fin)
        {
            var idempresaParameter = idempresa.HasValue ?
                new ObjectParameter("idempresa", idempresa) :
                new ObjectParameter("idempresa", typeof(int));
    
            var idnomina_tipoParameter = idnomina_tipo.HasValue ?
                new ObjectParameter("idnomina_tipo", idnomina_tipo) :
                new ObjectParameter("idnomina_tipo", typeof(int));
    
            var idRubro_25Parameter = idRubro_25.HasValue ?
                new ObjectParameter("idRubro_25", idRubro_25) :
                new ObjectParameter("idRubro_25", typeof(int));
    
            var idRubro_50Parameter = idRubro_50.HasValue ?
                new ObjectParameter("idRubro_50", idRubro_50) :
                new ObjectParameter("idRubro_50", typeof(int));
    
            var idRubro_100Parameter = idRubro_100.HasValue ?
                new ObjectParameter("idRubro_100", idRubro_100) :
                new ObjectParameter("idRubro_100", typeof(int));
    
            var fecha_inicioParameter = fecha_inicio.HasValue ?
                new ObjectParameter("fecha_inicio", fecha_inicio) :
                new ObjectParameter("fecha_inicio", typeof(System.DateTime));
    
            var fecha_finParameter = fecha_fin.HasValue ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spROL_Rpt020_Result>("spROL_Rpt020", idempresaParameter, idnomina_tipoParameter, idRubro_25Parameter, idRubro_50Parameter, idRubro_100Parameter, fecha_inicioParameter, fecha_finParameter);
        }
    }
}
