//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities_Inventario_General : DbContext
    {
        public Entities_Inventario_General()
            : base("name=Entities_Inventario_General")
        {
        }
        public void SetCommandTimeOut(int TimeOut)
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = TimeOut;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwINV_Rpt004> vwINV_Rpt004 { get; set; }
        public DbSet<vwINV_Rpt006> vwINV_Rpt006 { get; set; }
        public DbSet<vwINV_Rpt005> vwINV_Rpt005 { get; set; }
        public DbSet<vwINV_Rpt016> vwINV_Rpt016 { get; set; }
        public DbSet<vwINV_Rpt010> vwINV_Rpt010 { get; set; }
        public DbSet<vwINV_Rpt011> vwINV_Rpt011 { get; set; }
        public DbSet<vwINV_Rpt022> vwINV_Rpt022 { get; set; }
        public DbSet<vwINV_Rpt024> vwINV_Rpt024 { get; set; }
        public DbSet<vwINV_Rpt019> vwINV_Rpt019 { get; set; }
        public DbSet<vwINV_Rpt012> vwINV_Rpt012 { get; set; }
        public DbSet<vwINV_Rpt007> vwINV_Rpt007 { get; set; }
        public DbSet<vwINV_Rpt001> vwINV_Rpt001 { get; set; }
        public DbSet<vwINV_Rpt003> vwINV_Rpt003 { get; set; }
        public DbSet<vwINV_Rpt025> vwINV_Rpt025 { get; set; }
        public DbSet<vwINV_Rpt028> vwINV_Rpt028 { get; set; }
        public DbSet<vwINV_Rpt015> vwINV_Rpt015 { get; set; }
        public DbSet<vwINV_Rpt002> vwINV_Rpt002 { get; set; }
        public DbSet<vwINV_Rpt013> vwINV_Rpt013 { get; set; }
        public DbSet<vwINV_Rpt017> vwINV_Rpt017 { get; set; }
        public DbSet<vwINV_Rpt023> vwINV_Rpt023 { get; set; }
    
        public virtual ObjectResult<spINV_Rpt011_Result> spINV_Rpt011(Nullable<int> idEmpresa, Nullable<int> idSucursalIni, Nullable<int> idSucursalFin, Nullable<int> idBodegaIni, Nullable<int> idBodegaFin, Nullable<decimal> idProductoIni, Nullable<decimal> idProductoFin, Nullable<System.DateTime> fechaCorteIni)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var idSucursalIniParameter = idSucursalIni.HasValue ?
                new ObjectParameter("IdSucursalIni", idSucursalIni) :
                new ObjectParameter("IdSucursalIni", typeof(int));
    
            var idSucursalFinParameter = idSucursalFin.HasValue ?
                new ObjectParameter("IdSucursalFin", idSucursalFin) :
                new ObjectParameter("IdSucursalFin", typeof(int));
    
            var idBodegaIniParameter = idBodegaIni.HasValue ?
                new ObjectParameter("IdBodegaIni", idBodegaIni) :
                new ObjectParameter("IdBodegaIni", typeof(int));
    
            var idBodegaFinParameter = idBodegaFin.HasValue ?
                new ObjectParameter("IdBodegaFin", idBodegaFin) :
                new ObjectParameter("IdBodegaFin", typeof(int));
    
            var idProductoIniParameter = idProductoIni.HasValue ?
                new ObjectParameter("IdProductoIni", idProductoIni) :
                new ObjectParameter("IdProductoIni", typeof(decimal));
    
            var idProductoFinParameter = idProductoFin.HasValue ?
                new ObjectParameter("IdProductoFin", idProductoFin) :
                new ObjectParameter("IdProductoFin", typeof(decimal));
    
            var fechaCorteIniParameter = fechaCorteIni.HasValue ?
                new ObjectParameter("FechaCorteIni", fechaCorteIni) :
                new ObjectParameter("FechaCorteIni", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_Rpt011_Result>("spINV_Rpt011", idEmpresaParameter, idSucursalIniParameter, idSucursalFinParameter, idBodegaIniParameter, idBodegaFinParameter, idProductoIniParameter, idProductoFinParameter, fechaCorteIniParameter);
        }
    
        public virtual ObjectResult<spINV_Rpt018_Result> spINV_Rpt018(Nullable<int> i_IdEmpresa, Nullable<int> i_IdSucursalIni, Nullable<int> i_IdSucursalFin, Nullable<int> i_IdBodegaIni, Nullable<int> i_IdBodegaFin, Nullable<int> i_IdProductoIni, Nullable<int> i_IdProductoFin, Nullable<System.DateTime> i_FechaIni, Nullable<System.DateTime> i_FechaFin, Nullable<int> i_dias_stock, Nullable<bool> i_Mostrar_reg_en_cero)
        {
            var i_IdEmpresaParameter = i_IdEmpresa.HasValue ?
                new ObjectParameter("i_IdEmpresa", i_IdEmpresa) :
                new ObjectParameter("i_IdEmpresa", typeof(int));
    
            var i_IdSucursalIniParameter = i_IdSucursalIni.HasValue ?
                new ObjectParameter("i_IdSucursalIni", i_IdSucursalIni) :
                new ObjectParameter("i_IdSucursalIni", typeof(int));
    
            var i_IdSucursalFinParameter = i_IdSucursalFin.HasValue ?
                new ObjectParameter("i_IdSucursalFin", i_IdSucursalFin) :
                new ObjectParameter("i_IdSucursalFin", typeof(int));
    
            var i_IdBodegaIniParameter = i_IdBodegaIni.HasValue ?
                new ObjectParameter("i_IdBodegaIni", i_IdBodegaIni) :
                new ObjectParameter("i_IdBodegaIni", typeof(int));
    
            var i_IdBodegaFinParameter = i_IdBodegaFin.HasValue ?
                new ObjectParameter("i_IdBodegaFin", i_IdBodegaFin) :
                new ObjectParameter("i_IdBodegaFin", typeof(int));
    
            var i_IdProductoIniParameter = i_IdProductoIni.HasValue ?
                new ObjectParameter("i_IdProductoIni", i_IdProductoIni) :
                new ObjectParameter("i_IdProductoIni", typeof(int));
    
            var i_IdProductoFinParameter = i_IdProductoFin.HasValue ?
                new ObjectParameter("i_IdProductoFin", i_IdProductoFin) :
                new ObjectParameter("i_IdProductoFin", typeof(int));
    
            var i_FechaIniParameter = i_FechaIni.HasValue ?
                new ObjectParameter("i_FechaIni", i_FechaIni) :
                new ObjectParameter("i_FechaIni", typeof(System.DateTime));
    
            var i_FechaFinParameter = i_FechaFin.HasValue ?
                new ObjectParameter("i_FechaFin", i_FechaFin) :
                new ObjectParameter("i_FechaFin", typeof(System.DateTime));
    
            var i_dias_stockParameter = i_dias_stock.HasValue ?
                new ObjectParameter("i_dias_stock", i_dias_stock) :
                new ObjectParameter("i_dias_stock", typeof(int));
    
            var i_Mostrar_reg_en_ceroParameter = i_Mostrar_reg_en_cero.HasValue ?
                new ObjectParameter("i_Mostrar_reg_en_cero", i_Mostrar_reg_en_cero) :
                new ObjectParameter("i_Mostrar_reg_en_cero", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_Rpt018_Result>("spINV_Rpt018", i_IdEmpresaParameter, i_IdSucursalIniParameter, i_IdSucursalFinParameter, i_IdBodegaIniParameter, i_IdBodegaFinParameter, i_IdProductoIniParameter, i_IdProductoFinParameter, i_FechaIniParameter, i_FechaFinParameter, i_dias_stockParameter, i_Mostrar_reg_en_ceroParameter);
        }
    
        public virtual ObjectResult<spINV_Rpt021_Result> spINV_Rpt021(Nullable<int> i_IdEmpresa, Nullable<int> i_IdSucursalIni, Nullable<int> i_IdSucursalFin, Nullable<int> i_IdBodegaIni, Nullable<int> i_IdBodegaFin, Nullable<int> i_IdProductoIni, Nullable<int> i_IdProductoFin, Nullable<System.DateTime> i_FechaIni, Nullable<System.DateTime> i_FechaFin, Nullable<int> i_dias_stock, Nullable<bool> i_Mostrar_reg_en_cero)
        {
            var i_IdEmpresaParameter = i_IdEmpresa.HasValue ?
                new ObjectParameter("i_IdEmpresa", i_IdEmpresa) :
                new ObjectParameter("i_IdEmpresa", typeof(int));
    
            var i_IdSucursalIniParameter = i_IdSucursalIni.HasValue ?
                new ObjectParameter("i_IdSucursalIni", i_IdSucursalIni) :
                new ObjectParameter("i_IdSucursalIni", typeof(int));
    
            var i_IdSucursalFinParameter = i_IdSucursalFin.HasValue ?
                new ObjectParameter("i_IdSucursalFin", i_IdSucursalFin) :
                new ObjectParameter("i_IdSucursalFin", typeof(int));
    
            var i_IdBodegaIniParameter = i_IdBodegaIni.HasValue ?
                new ObjectParameter("i_IdBodegaIni", i_IdBodegaIni) :
                new ObjectParameter("i_IdBodegaIni", typeof(int));
    
            var i_IdBodegaFinParameter = i_IdBodegaFin.HasValue ?
                new ObjectParameter("i_IdBodegaFin", i_IdBodegaFin) :
                new ObjectParameter("i_IdBodegaFin", typeof(int));
    
            var i_IdProductoIniParameter = i_IdProductoIni.HasValue ?
                new ObjectParameter("i_IdProductoIni", i_IdProductoIni) :
                new ObjectParameter("i_IdProductoIni", typeof(int));
    
            var i_IdProductoFinParameter = i_IdProductoFin.HasValue ?
                new ObjectParameter("i_IdProductoFin", i_IdProductoFin) :
                new ObjectParameter("i_IdProductoFin", typeof(int));
    
            var i_FechaIniParameter = i_FechaIni.HasValue ?
                new ObjectParameter("i_FechaIni", i_FechaIni) :
                new ObjectParameter("i_FechaIni", typeof(System.DateTime));
    
            var i_FechaFinParameter = i_FechaFin.HasValue ?
                new ObjectParameter("i_FechaFin", i_FechaFin) :
                new ObjectParameter("i_FechaFin", typeof(System.DateTime));
    
            var i_dias_stockParameter = i_dias_stock.HasValue ?
                new ObjectParameter("i_dias_stock", i_dias_stock) :
                new ObjectParameter("i_dias_stock", typeof(int));
    
            var i_Mostrar_reg_en_ceroParameter = i_Mostrar_reg_en_cero.HasValue ?
                new ObjectParameter("i_Mostrar_reg_en_cero", i_Mostrar_reg_en_cero) :
                new ObjectParameter("i_Mostrar_reg_en_cero", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_Rpt021_Result>("spINV_Rpt021", i_IdEmpresaParameter, i_IdSucursalIniParameter, i_IdSucursalFinParameter, i_IdBodegaIniParameter, i_IdBodegaFinParameter, i_IdProductoIniParameter, i_IdProductoFinParameter, i_FechaIniParameter, i_FechaFinParameter, i_dias_stockParameter, i_Mostrar_reg_en_ceroParameter);
        }
    
        public virtual ObjectResult<spINV_Rpt026_Result> spINV_Rpt026(Nullable<int> idEmpresa, Nullable<int> idSucursal_ini, Nullable<int> idSucursal_fin, Nullable<int> idBodega_ini, Nullable<int> idBodega_fin, Nullable<System.DateTime> fecha_ini, Nullable<System.DateTime> fecha_fin)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var idSucursal_iniParameter = idSucursal_ini.HasValue ?
                new ObjectParameter("IdSucursal_ini", idSucursal_ini) :
                new ObjectParameter("IdSucursal_ini", typeof(int));
    
            var idSucursal_finParameter = idSucursal_fin.HasValue ?
                new ObjectParameter("IdSucursal_fin", idSucursal_fin) :
                new ObjectParameter("IdSucursal_fin", typeof(int));
    
            var idBodega_iniParameter = idBodega_ini.HasValue ?
                new ObjectParameter("IdBodega_ini", idBodega_ini) :
                new ObjectParameter("IdBodega_ini", typeof(int));
    
            var idBodega_finParameter = idBodega_fin.HasValue ?
                new ObjectParameter("IdBodega_fin", idBodega_fin) :
                new ObjectParameter("IdBodega_fin", typeof(int));
    
            var fecha_iniParameter = fecha_ini.HasValue ?
                new ObjectParameter("Fecha_ini", fecha_ini) :
                new ObjectParameter("Fecha_ini", typeof(System.DateTime));
    
            var fecha_finParameter = fecha_fin.HasValue ?
                new ObjectParameter("Fecha_fin", fecha_fin) :
                new ObjectParameter("Fecha_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_Rpt026_Result>("spINV_Rpt026", idEmpresaParameter, idSucursal_iniParameter, idSucursal_finParameter, idBodega_iniParameter, idBodega_finParameter, fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<spINV_Rpt010_Result> spINV_Rpt010(Nullable<int> idEmpresa, Nullable<int> idSucursal_ini, Nullable<int> idSucursal_fin, Nullable<int> idBodega_ini, Nullable<int> idBodega_fin, Nullable<decimal> idProducto_ini, Nullable<decimal> idProducto_fin, Nullable<System.DateTime> fecha_ini, Nullable<System.DateTime> fecha_fin, string idUsuario, Nullable<bool> no_Mostrar_valores_en_0, Nullable<bool> mostrar_detallado)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var idSucursal_iniParameter = idSucursal_ini.HasValue ?
                new ObjectParameter("IdSucursal_ini", idSucursal_ini) :
                new ObjectParameter("IdSucursal_ini", typeof(int));
    
            var idSucursal_finParameter = idSucursal_fin.HasValue ?
                new ObjectParameter("IdSucursal_fin", idSucursal_fin) :
                new ObjectParameter("IdSucursal_fin", typeof(int));
    
            var idBodega_iniParameter = idBodega_ini.HasValue ?
                new ObjectParameter("IdBodega_ini", idBodega_ini) :
                new ObjectParameter("IdBodega_ini", typeof(int));
    
            var idBodega_finParameter = idBodega_fin.HasValue ?
                new ObjectParameter("IdBodega_fin", idBodega_fin) :
                new ObjectParameter("IdBodega_fin", typeof(int));
    
            var idProducto_iniParameter = idProducto_ini.HasValue ?
                new ObjectParameter("IdProducto_ini", idProducto_ini) :
                new ObjectParameter("IdProducto_ini", typeof(decimal));
    
            var idProducto_finParameter = idProducto_fin.HasValue ?
                new ObjectParameter("IdProducto_fin", idProducto_fin) :
                new ObjectParameter("IdProducto_fin", typeof(decimal));
    
            var fecha_iniParameter = fecha_ini.HasValue ?
                new ObjectParameter("Fecha_ini", fecha_ini) :
                new ObjectParameter("Fecha_ini", typeof(System.DateTime));
    
            var fecha_finParameter = fecha_fin.HasValue ?
                new ObjectParameter("Fecha_fin", fecha_fin) :
                new ObjectParameter("Fecha_fin", typeof(System.DateTime));
    
            var idUsuarioParameter = idUsuario != null ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(string));
    
            var no_Mostrar_valores_en_0Parameter = no_Mostrar_valores_en_0.HasValue ?
                new ObjectParameter("No_Mostrar_valores_en_0", no_Mostrar_valores_en_0) :
                new ObjectParameter("No_Mostrar_valores_en_0", typeof(bool));
    
            var mostrar_detalladoParameter = mostrar_detallado.HasValue ?
                new ObjectParameter("Mostrar_detallado", mostrar_detallado) :
                new ObjectParameter("Mostrar_detallado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_Rpt010_Result>("spINV_Rpt010", idEmpresaParameter, idSucursal_iniParameter, idSucursal_finParameter, idBodega_iniParameter, idBodega_finParameter, idProducto_iniParameter, idProducto_finParameter, fecha_iniParameter, fecha_finParameter, idUsuarioParameter, no_Mostrar_valores_en_0Parameter, mostrar_detalladoParameter);
        }
    
        public virtual ObjectResult<spINV_Rpt027_Result> spINV_Rpt027(Nullable<int> idEmpresa, Nullable<int> idSucursal_ini, Nullable<int> idSucursal_fin, Nullable<int> idBodega_ini, Nullable<int> idBodega_fin, Nullable<decimal> idProducto_ini, Nullable<decimal> idProducto_fin, Nullable<System.DateTime> fecha_ini, Nullable<System.DateTime> fecha_fin, string idUsuario, Nullable<bool> no_Mostrar_valores_en_0, Nullable<bool> mostrar_detallado)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var idSucursal_iniParameter = idSucursal_ini.HasValue ?
                new ObjectParameter("IdSucursal_ini", idSucursal_ini) :
                new ObjectParameter("IdSucursal_ini", typeof(int));
    
            var idSucursal_finParameter = idSucursal_fin.HasValue ?
                new ObjectParameter("IdSucursal_fin", idSucursal_fin) :
                new ObjectParameter("IdSucursal_fin", typeof(int));
    
            var idBodega_iniParameter = idBodega_ini.HasValue ?
                new ObjectParameter("IdBodega_ini", idBodega_ini) :
                new ObjectParameter("IdBodega_ini", typeof(int));
    
            var idBodega_finParameter = idBodega_fin.HasValue ?
                new ObjectParameter("IdBodega_fin", idBodega_fin) :
                new ObjectParameter("IdBodega_fin", typeof(int));
    
            var idProducto_iniParameter = idProducto_ini.HasValue ?
                new ObjectParameter("IdProducto_ini", idProducto_ini) :
                new ObjectParameter("IdProducto_ini", typeof(decimal));
    
            var idProducto_finParameter = idProducto_fin.HasValue ?
                new ObjectParameter("IdProducto_fin", idProducto_fin) :
                new ObjectParameter("IdProducto_fin", typeof(decimal));
    
            var fecha_iniParameter = fecha_ini.HasValue ?
                new ObjectParameter("Fecha_ini", fecha_ini) :
                new ObjectParameter("Fecha_ini", typeof(System.DateTime));
    
            var fecha_finParameter = fecha_fin.HasValue ?
                new ObjectParameter("Fecha_fin", fecha_fin) :
                new ObjectParameter("Fecha_fin", typeof(System.DateTime));
    
            var idUsuarioParameter = idUsuario != null ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(string));
    
            var no_Mostrar_valores_en_0Parameter = no_Mostrar_valores_en_0.HasValue ?
                new ObjectParameter("No_Mostrar_valores_en_0", no_Mostrar_valores_en_0) :
                new ObjectParameter("No_Mostrar_valores_en_0", typeof(bool));
    
            var mostrar_detalladoParameter = mostrar_detallado.HasValue ?
                new ObjectParameter("Mostrar_detallado", mostrar_detallado) :
                new ObjectParameter("Mostrar_detallado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_Rpt027_Result>("spINV_Rpt027", idEmpresaParameter, idSucursal_iniParameter, idSucursal_finParameter, idBodega_iniParameter, idBodega_finParameter, idProducto_iniParameter, idProducto_finParameter, fecha_iniParameter, fecha_finParameter, idUsuarioParameter, no_Mostrar_valores_en_0Parameter, mostrar_detalladoParameter);
        }
    
        public virtual ObjectResult<spINV_Rpt029_Result> spINV_Rpt029(Nullable<int> idEmpresa, Nullable<int> idSucursal_ini, Nullable<int> idSucursal_fin, Nullable<int> idBodega_ini, Nullable<int> idBodega_fin, Nullable<System.DateTime> fecha_corte)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var idSucursal_iniParameter = idSucursal_ini.HasValue ?
                new ObjectParameter("IdSucursal_ini", idSucursal_ini) :
                new ObjectParameter("IdSucursal_ini", typeof(int));
    
            var idSucursal_finParameter = idSucursal_fin.HasValue ?
                new ObjectParameter("IdSucursal_fin", idSucursal_fin) :
                new ObjectParameter("IdSucursal_fin", typeof(int));
    
            var idBodega_iniParameter = idBodega_ini.HasValue ?
                new ObjectParameter("IdBodega_ini", idBodega_ini) :
                new ObjectParameter("IdBodega_ini", typeof(int));
    
            var idBodega_finParameter = idBodega_fin.HasValue ?
                new ObjectParameter("IdBodega_fin", idBodega_fin) :
                new ObjectParameter("IdBodega_fin", typeof(int));
    
            var fecha_corteParameter = fecha_corte.HasValue ?
                new ObjectParameter("fecha_corte", fecha_corte) :
                new ObjectParameter("fecha_corte", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_Rpt029_Result>("spINV_Rpt029", idEmpresaParameter, idSucursal_iniParameter, idSucursal_finParameter, idBodega_iniParameter, idBodega_finParameter, fecha_corteParameter);
        }
    
        public virtual ObjectResult<spINV_Rpt009_Result> spINV_Rpt009(Nullable<int> idEmpresa, Nullable<int> idSucursal_ini, Nullable<int> idSucursal_fin, Nullable<int> idBodega_ini, Nullable<int> idBodega_fin, Nullable<decimal> idProducto_ini, Nullable<decimal> idProducto_fin, Nullable<System.DateTime> fecha_corte)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var idSucursal_iniParameter = idSucursal_ini.HasValue ?
                new ObjectParameter("IdSucursal_ini", idSucursal_ini) :
                new ObjectParameter("IdSucursal_ini", typeof(int));
    
            var idSucursal_finParameter = idSucursal_fin.HasValue ?
                new ObjectParameter("IdSucursal_fin", idSucursal_fin) :
                new ObjectParameter("IdSucursal_fin", typeof(int));
    
            var idBodega_iniParameter = idBodega_ini.HasValue ?
                new ObjectParameter("IdBodega_ini", idBodega_ini) :
                new ObjectParameter("IdBodega_ini", typeof(int));
    
            var idBodega_finParameter = idBodega_fin.HasValue ?
                new ObjectParameter("IdBodega_fin", idBodega_fin) :
                new ObjectParameter("IdBodega_fin", typeof(int));
    
            var idProducto_iniParameter = idProducto_ini.HasValue ?
                new ObjectParameter("IdProducto_ini", idProducto_ini) :
                new ObjectParameter("IdProducto_ini", typeof(decimal));
    
            var idProducto_finParameter = idProducto_fin.HasValue ?
                new ObjectParameter("IdProducto_fin", idProducto_fin) :
                new ObjectParameter("IdProducto_fin", typeof(decimal));
    
            var fecha_corteParameter = fecha_corte.HasValue ?
                new ObjectParameter("fecha_corte", fecha_corte) :
                new ObjectParameter("fecha_corte", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spINV_Rpt009_Result>("spINV_Rpt009", idEmpresaParameter, idSucursal_iniParameter, idSucursal_finParameter, idBodega_iniParameter, idBodega_finParameter, idProducto_iniParameter, idProducto_finParameter, fecha_corteParameter);
        }
    }
}
