//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntitiesBancos_Reporte_Ge : DbContext
    {
        public EntitiesBancos_Reporte_Ge()
            : base("name=EntitiesBancos_Reporte_Ge")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwBAN_Rpt001> vwBAN_Rpt001 { get; set; }
        public DbSet<vwBAN_Rpt004> vwBAN_Rpt004 { get; set; }
        public DbSet<vwBAN_Rpt002> vwBAN_Rpt002 { get; set; }
        public DbSet<vwBAN_Rpt003> vwBAN_Rpt003 { get; set; }
        public DbSet<vwBAN_Rpt010> vwBAN_Rpt010 { get; set; }
        public DbSet<vwBAN_Rpt012> vwBAN_Rpt012 { get; set; }
        public DbSet<vwBAN_Rpt014> vwBAN_Rpt014 { get; set; }
        public DbSet<vwBAN_Rpt015> vwBAN_Rpt015 { get; set; }
        public DbSet<vwBAN_Rpt016> vwBAN_Rpt016 { get; set; }
        public DbSet<vwBAN_Rpt006> vwBAN_Rpt006 { get; set; }
        public DbSet<vwBAN_Rpt005> vwBAN_Rpt005 { get; set; }
        public DbSet<vwBAN_Rpt013> vwBAN_Rpt013 { get; set; }
        public DbSet<vwBAN_Rpt019> vwBAN_Rpt019 { get; set; }
        public DbSet<vwBAN_Rpt018> vwBAN_Rpt018 { get; set; }
    
        public virtual ObjectResult<spBAN_Rpt008_Result> spBAN_Rpt008(Nullable<int> idEmpresa, Nullable<System.DateTime> fecha_Ini, Nullable<System.DateTime> fecha_Fin)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var fecha_IniParameter = fecha_Ini.HasValue ?
                new ObjectParameter("fecha_Ini", fecha_Ini) :
                new ObjectParameter("fecha_Ini", typeof(System.DateTime));
    
            var fecha_FinParameter = fecha_Fin.HasValue ?
                new ObjectParameter("fecha_Fin", fecha_Fin) :
                new ObjectParameter("fecha_Fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBAN_Rpt008_Result>("spBAN_Rpt008", idEmpresaParameter, fecha_IniParameter, fecha_FinParameter);
        }
    
        public virtual ObjectResult<spBAN_Rpt009_Result> spBAN_Rpt009(Nullable<int> idEmpresa, Nullable<System.DateTime> fecha_ini, Nullable<System.DateTime> fecha_fin)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var fecha_iniParameter = fecha_ini.HasValue ?
                new ObjectParameter("Fecha_ini", fecha_ini) :
                new ObjectParameter("Fecha_ini", typeof(System.DateTime));
    
            var fecha_finParameter = fecha_fin.HasValue ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBAN_Rpt009_Result>("spBAN_Rpt009", idEmpresaParameter, fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<spBAN_Rpt011_Result> spBAN_Rpt011(Nullable<int> idEmpresa, Nullable<int> idBanco, Nullable<decimal> idConciliacion)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var idBancoParameter = idBanco.HasValue ?
                new ObjectParameter("IdBanco", idBanco) :
                new ObjectParameter("IdBanco", typeof(int));
    
            var idConciliacionParameter = idConciliacion.HasValue ?
                new ObjectParameter("IdConciliacion", idConciliacion) :
                new ObjectParameter("IdConciliacion", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBAN_Rpt011_Result>("spBAN_Rpt011", idEmpresaParameter, idBancoParameter, idConciliacionParameter);
        }
    
        public virtual ObjectResult<spBAN_Rpt007_saldos_Result> spBAN_Rpt007_saldos(Nullable<int> idEmpresa, Nullable<System.DateTime> fecha_ini, Nullable<System.DateTime> fecha_fin, string idUsuario)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var fecha_iniParameter = fecha_ini.HasValue ?
                new ObjectParameter("Fecha_ini", fecha_ini) :
                new ObjectParameter("Fecha_ini", typeof(System.DateTime));
    
            var fecha_finParameter = fecha_fin.HasValue ?
                new ObjectParameter("Fecha_fin", fecha_fin) :
                new ObjectParameter("Fecha_fin", typeof(System.DateTime));
    
            var idUsuarioParameter = idUsuario != null ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBAN_Rpt007_saldos_Result>("spBAN_Rpt007_saldos", idEmpresaParameter, fecha_iniParameter, fecha_finParameter, idUsuarioParameter);
        }
    
        public virtual ObjectResult<spBAN_Rpt010_Result> spBAN_Rpt010(Nullable<int> idEmpresa, Nullable<int> idBanco, Nullable<System.DateTime> fecha_ini, Nullable<System.DateTime> fecha_fin)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var idBancoParameter = idBanco.HasValue ?
                new ObjectParameter("IdBanco", idBanco) :
                new ObjectParameter("IdBanco", typeof(int));
    
            var fecha_iniParameter = fecha_ini.HasValue ?
                new ObjectParameter("Fecha_ini", fecha_ini) :
                new ObjectParameter("Fecha_ini", typeof(System.DateTime));
    
            var fecha_finParameter = fecha_fin.HasValue ?
                new ObjectParameter("Fecha_fin", fecha_fin) :
                new ObjectParameter("Fecha_fin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBAN_Rpt010_Result>("spBAN_Rpt010", idEmpresaParameter, idBancoParameter, fecha_iniParameter, fecha_finParameter);
        }
    
        public virtual ObjectResult<spBAN_Rpt007_Result> spBAN_Rpt007(Nullable<int> idEmpresa, Nullable<System.DateTime> fecha_Ini, Nullable<System.DateTime> fecha_Fin, Nullable<int> idTipoFlujo_ini, Nullable<int> idTipoFlujo_fin, Nullable<int> idBanco_ini, Nullable<int> idBanco_fin, Nullable<bool> mostrar_detallado, Nullable<bool> mostrar_registros_en_conciliacion)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var fecha_IniParameter = fecha_Ini.HasValue ?
                new ObjectParameter("fecha_Ini", fecha_Ini) :
                new ObjectParameter("fecha_Ini", typeof(System.DateTime));
    
            var fecha_FinParameter = fecha_Fin.HasValue ?
                new ObjectParameter("fecha_Fin", fecha_Fin) :
                new ObjectParameter("fecha_Fin", typeof(System.DateTime));
    
            var idTipoFlujo_iniParameter = idTipoFlujo_ini.HasValue ?
                new ObjectParameter("IdTipoFlujo_ini", idTipoFlujo_ini) :
                new ObjectParameter("IdTipoFlujo_ini", typeof(int));
    
            var idTipoFlujo_finParameter = idTipoFlujo_fin.HasValue ?
                new ObjectParameter("IdTipoFlujo_fin", idTipoFlujo_fin) :
                new ObjectParameter("IdTipoFlujo_fin", typeof(int));
    
            var idBanco_iniParameter = idBanco_ini.HasValue ?
                new ObjectParameter("IdBanco_ini", idBanco_ini) :
                new ObjectParameter("IdBanco_ini", typeof(int));
    
            var idBanco_finParameter = idBanco_fin.HasValue ?
                new ObjectParameter("IdBanco_fin", idBanco_fin) :
                new ObjectParameter("IdBanco_fin", typeof(int));
    
            var mostrar_detalladoParameter = mostrar_detallado.HasValue ?
                new ObjectParameter("Mostrar_detallado", mostrar_detallado) :
                new ObjectParameter("Mostrar_detallado", typeof(bool));
    
            var mostrar_registros_en_conciliacionParameter = mostrar_registros_en_conciliacion.HasValue ?
                new ObjectParameter("Mostrar_registros_en_conciliacion", mostrar_registros_en_conciliacion) :
                new ObjectParameter("Mostrar_registros_en_conciliacion", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBAN_Rpt007_Result>("spBAN_Rpt007", idEmpresaParameter, fecha_IniParameter, fecha_FinParameter, idTipoFlujo_iniParameter, idTipoFlujo_finParameter, idBanco_iniParameter, idBanco_finParameter, mostrar_detalladoParameter, mostrar_registros_en_conciliacionParameter);
        }
    }
}
