//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCXC_Rpt016
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdCobro { get; set; }
        public int secuencial { get; set; }
        public Nullable<int> IdBodega_Cbte { get; set; }
        public decimal IdCbte_vta_nota { get; set; }
        public string IdCobro_tipo { get; set; }
        public string CodDocumentoTipo { get; set; }
        public string Serie1 { get; set; }
        public string Serie2 { get; set; }
        public string NumNota_Impresa { get; set; }
        public decimal IdCliente { get; set; }
        public string nom_cliente { get; set; }
        public string sc_observacion { get; set; }
        public System.DateTime cr_fecha { get; set; }
        public string tc_descripcion { get; set; }
        public Nullable<double> PorcentajeRet { get; set; }
        public double dc_ValorPago { get; set; }
        public string cr_NumDocumento { get; set; }
        public Nullable<double> Base { get; set; }
        public string num_documento { get; set; }
        public Nullable<double> sc_subtotal { get; set; }
        public Nullable<double> sc_iva { get; set; }
        public Nullable<double> sc_total { get; set; }
    }
}
