//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCXP_Rpt012
    {
        public int IdEmpresa { get; set; }
        public decimal IdCbteCble_Ogiro { get; set; }
        public int IdTipoCbte_Ogiro { get; set; }
        public string IdOrden_giro_Tipo { get; set; }
        public string Documento { get; set; }
        public string nom_tipo_doc { get; set; }
        public string cod_tipo_doc { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal IdProveedor { get; set; }
        public string nom_proveedor { get; set; }
        public string Observacion { get; set; }
        public Nullable<double> ValorAPagar { get; set; }
        public Nullable<double> TotalPagado { get; set; }
        public Nullable<double> Saldo { get; set; }
        public string TipoRegistro { get; set; }
        public int IdCalendario { get; set; }
        public string NombreCortoFecha { get; set; }
        public string NombreMes { get; set; }
        public Nullable<int> IdMes { get; set; }
        public Nullable<int> AnioFiscal { get; set; }
        public System.DateTime co_FechaFactura_vct { get; set; }
    }
}
