//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwINV_Rpt005
    {
        public int IdEmpresa { get; set; }
        public decimal IdProducto { get; set; }
        public string pr_codigo { get; set; }
        public string pr_descripcion { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public int IdSucursal { get; set; }
        public double dm_stock_ante { get; set; }
        public double dm_cantidad { get; set; }
        public double dm_stock_actu { get; set; }
        public double mv_costo { get; set; }
        public decimal IdNumMovi { get; set; }
        public int IdMovi_inven_tipo { get; set; }
        public string TipoMovimiento { get; set; }
        public double dm_cantidad_sinConversion { get; set; }
        public Nullable<double> mv_costo_sinConversion { get; set; }
        public string IdUnidadMedida { get; set; }
        public string IdUnidadMedida_sinConversion { get; set; }
        public string signo { get; set; }
    }
}
