//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Reportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwROL_Rpt011
    {
        public int IdEmpresa { get; set; }
        public decimal IdEmpleado { get; set; }
        public decimal IdArchivo { get; set; }
        public double Valor { get; set; }
        public string NombreCompleto { get; set; }
        public string Cedula { get; set; }
        public string NoCuenta { get; set; }
        public string CodigoEmpleado { get; set; }
        public string TipoCuenta { get; set; }
        public string em_SeAcreditaBanco { get; set; }
        public string EstadoEmpleado { get; set; }
        public string IdBancoEmpleado { get; set; }
        public Nullable<int> IdDivisionEmpleado { get; set; }
        public Nullable<int> IdArea { get; set; }
        public string StatusEmpleado { get; set; }
        public int IdNomina { get; set; }
        public int IdNominaTipo { get; set; }
        public int IdPeriodo { get; set; }
        public string DescripcionNominaTipo { get; set; }
        public string DescripcionNominaTipoLiqui { get; set; }
        public string IdBancoArchivo { get; set; }
        public Nullable<int> IdDivisionArchivo { get; set; }
        public string DescripcionBancoEmpleado { get; set; }
        public System.DateTime FechaInicial { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> pagacheque { get; set; }
    }
}
