//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_Aspirante
    {
        public Aca_Aspirante()
        {
            this.Aca_Admision = new HashSet<Aca_Admision>();
        }
    
        public int IdInstitucion { get; set; }
        public decimal IdAspirante { get; set; }
        public string cod_aspirante { get; set; }
        public string lugar { get; set; }
        public string IdPais_Nacionalidad { get; set; }
        public string barrio { get; set; }
        public byte[] foto { get; set; }
        public string estado { get; set; }
        public string cod_alterno { get; set; }
        public decimal IdPersona { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string MotivoAnulacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string UsuarioAnulacion { get; set; }
        public string estado_alumno { get; set; }
        public string estado_admision { get; set; }
    
        public virtual ICollection<Aca_Admision> Aca_Admision { get; set; }
        public virtual Aca_Institucion Aca_Institucion { get; set; }
    }
}
