//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_Rubro_Tipo
    {
        public Aca_Rubro_Tipo()
        {
            this.Aca_Rubro = new HashSet<Aca_Rubro>();
        }
    
        public int IdTipoRubro { get; set; }
        public string codTipoRubro { get; set; }
        public string descripcion_tipo { get; set; }
        public string estado { get; set; }
        public string IdRubroComportamiento_cat { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string UsuarioAnulacion { get; set; }
        public string MotivoAnulacion { get; set; }
    
        public virtual Aca_Catalogo Aca_Catalogo { get; set; }
        public virtual ICollection<Aca_Rubro> Aca_Rubro { get; set; }
    }
}
