//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aca_Seccion
    {
        public Aca_Seccion()
        {
            this.Aca_curso = new HashSet<Aca_curso>();
        }
    
        public int IdSeccion { get; set; }
        public int IdJornada { get; set; }
        public string CodSeccion { get; set; }
        public string CodAlterno_Sec { get; set; }
        public string Descripcion_secc { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string UsuarioAnulacion { get; set; }
        public string MotivoAnulacion { get; set; }
    
        public virtual ICollection<Aca_curso> Aca_curso { get; set; }
        public virtual Aca_Jornada Aca_Jornada { get; set; }
    }
}
