//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAca_Institucion_x_Sede_x_Jorn_x_Sec_Curso_x_Para
    {
        public Nullable<int> IdInstitucion { get; set; }
        public string Id { get; set; }
        public string IdPadre { get; set; }
        public string Nombre { get; set; }
        public string Estado { get; set; }
        public int Nivel { get; set; }
        public Nullable<int> IdSede { get; set; }
        public Nullable<int> IdJornada { get; set; }
        public Nullable<int> IdSeccion { get; set; }
        public Nullable<int> IdCurso { get; set; }
        public Nullable<int> IdParalelo { get; set; }
    }
}
