//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.Talme
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesFacturacion_Rpt : DbContext
    {
        public EntitiesFacturacion_Rpt()
            : base("name=EntitiesFacturacion_Rpt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwFAC_CUS_TAL_Rpt001> vwFAC_CUS_TAL_Rpt001 { get; set; }
        public DbSet<vwFAC_CUS_TAL_Rpt002> vwFAC_CUS_TAL_Rpt002 { get; set; }
        public DbSet<vwFAC_CUS_TAL_Rpt003> vwFAC_CUS_TAL_Rpt003 { get; set; }
        public DbSet<vwFAC_CUS_TAL_Rpt004> vwFAC_CUS_TAL_Rpt004 { get; set; }
        public DbSet<vwFAC_CUS_TAL_Rpt006> vwFAC_CUS_TAL_Rpt006 { get; set; }
    }
}
