//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.Talme
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFAC_CUS_TAL_Rpt003
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdGuiaRemision { get; set; }
        public string CodGuiaRemision { get; set; }
        public string Serie1 { get; set; }
        public string Serie2 { get; set; }
        public string NumGuia_Preimpresa { get; set; }
        public decimal IdCliente { get; set; }
        public int IdVendedor { get; set; }
        public decimal IdTransportista { get; set; }
        public System.DateTime gi_fecha { get; set; }
        public Nullable<decimal> gi_plazo { get; set; }
        public Nullable<System.DateTime> gi_fech_venc { get; set; }
        public string gi_Observacion { get; set; }
        public double gi_TotalKilos { get; set; }
        public double gi_TotalQuintales { get; set; }
        public string IdUsuario { get; set; }
        public double gi_flete { get; set; }
        public double gi_interes { get; set; }
        public double gi_seguro { get; set; }
        public double gi_OtroValor1 { get; set; }
        public double gi_OtroValor2 { get; set; }
        public int Secuencia { get; set; }
        public decimal IdProducto { get; set; }
        public double gi_cantidad { get; set; }
        public double gi_Precio { get; set; }
        public double gi_PorDescUnitario { get; set; }
        public double gi_DescUnitario { get; set; }
        public double gi_PrecioFinal { get; set; }
        public double gi_Subtotal { get; set; }
        public double gi_iva { get; set; }
        public double gi_total { get; set; }
        public string gi_detallexItems { get; set; }
        public Nullable<double> gi_peso { get; set; }
        public string nom_empresa { get; set; }
        public string ruc_empresa { get; set; }
        public byte[] logo_empresa { get; set; }
        public string nom_sucursal { get; set; }
        public string nom_bodega { get; set; }
        public string nom_cliente { get; set; }
        public string cod_producto { get; set; }
        public string nom_producto { get; set; }
        public string nom_transportista { get; set; }
        public string razon_social_transportista { get; set; }
        public string cedula_ruc_transportista { get; set; }
        public string cedula_ruc_cliente { get; set; }
        public string direccion_cliente { get; set; }
        public string direccion_empresa { get; set; }
    }
}
