//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.Talme
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFAC_CUS_TAL_Rpt001
    {
        public int IdEmpresa { get; set; }
        public string em_nombre { get; set; }
        public int IdSucursal { get; set; }
        public string Su_Descripcion { get; set; }
        public int IdBodega { get; set; }
        public string bo_Descripcion { get; set; }
        public decimal IdPedido { get; set; }
        public decimal IdCliente { get; set; }
        public decimal IdPersona { get; set; }
        public string pe_nombreCompleto { get; set; }
        public System.DateTime cp_fecha { get; set; }
        public int cp_diasPlazo { get; set; }
        public System.DateTime cp_fechaVencimiento { get; set; }
        public string cp_observacion { get; set; }
        public string IdEstadoAprobacion { get; set; }
        public int Secuencial { get; set; }
        public decimal IdProducto { get; set; }
        public string pr_codigo { get; set; }
        public string pr_descripcion { get; set; }
        public double dp_cantidad { get; set; }
        public double dp_precio { get; set; }
        public double dp_PorDescuento { get; set; }
        public double cp_desUni { get; set; }
        public double cp_PrecioFinal { get; set; }
        public double dp_subtotal { get; set; }
        public double dp_iva { get; set; }
        public double dp_total { get; set; }
        public Nullable<double> dp_peso { get; set; }
        public decimal interes { get; set; }
        public decimal transporte { get; set; }
        public decimal otro1 { get; set; }
        public decimal otro2 { get; set; }
        public string IdEstadoProduccion { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string pe_direccion { get; set; }
        public string pe_telefonoOfic { get; set; }
        public string pe_telefonoCasa { get; set; }
        public string pe_correo { get; set; }
        public string pe_razonSocial { get; set; }
    }
}
