CREATE TABLE [dbo].[Aca_Admision] (
    [IdInstitucion]                     INT           NOT NULL,
    [IdAdmision]                        NUMERIC (18)  NOT NULL,
    [cod_Admision]                      VARCHAR (25)  NOT NULL,
    [IdAspirante]                       NUMERIC (18)  NOT NULL,
    [IdAnioLectivo]                     INT           NOT NULL,
    [IdCurso]                           INT           NOT NULL,
    [IdCatalogo_Grupo_Fami_convivencia] VARCHAR (35)  NOT NULL,
    [IdCatalogo_Tipo_Religion]          VARCHAR (35)  NOT NULL,
    [IdCatalogo_Tipo_Sangre]            VARCHAR (35)  NOT NULL,
    [IdCatalogo_Idioma_Nati]            VARCHAR (35)  NOT NULL,
    [Telefono_Emer]                     VARCHAR (50)  NOT NULL,
    [Posee_Discapacidad]                BIT           NOT NULL,
    [Hijo_unico]                        BIT           NOT NULL,
    [Actu_Asis_Estable_Edu]             BIT           NOT NULL,
    [Estable_Edu_donde_asis]            VARCHAR (150) NOT NULL,
    [Tiene_Her_otros_cole]              BIT           NOT NULL,
    [Tiene_Her_nuestro_cole]            BIT           NOT NULL,
    [En_q_grado_tiene_her]              VARCHAR (150) NOT NULL,
    [Hijo_de_prof_del_coleg]            BIT           NOT NULL,
    [cod_Alterno]                       VARCHAR (25)  NOT NULL,
    [FechaCreacion]                     DATETIME      NULL,
    [FechaModificacion]                 DATETIME      NULL,
    [FechaAnulacion]                    DATETIME      NULL,
    [UsuarioCreacion]                   VARCHAR (25)  NULL,
    [UsuarioModificacion]               VARCHAR (25)  NULL,
    [UsuarioAnulacion]                  VARCHAR (25)  NULL,
    [Estado]                            CHAR (1)      NOT NULL,
    [MotivoAnulacion]                   VARCHAR (150) NULL,
    CONSTRAINT [PK_Aca_Adminision] PRIMARY KEY CLUSTERED ([IdInstitucion] ASC, [IdAdmision] ASC),
    CONSTRAINT [FK_Aca_Admision_Aca_Anio_Lectivo] FOREIGN KEY ([IdInstitucion], [IdAnioLectivo]) REFERENCES [dbo].[Aca_Anio_Lectivo] ([IdInstitucion], [IdAnioLectivo]),
    CONSTRAINT [FK_Aca_Admision_Aca_Aspirante] FOREIGN KEY ([IdInstitucion], [IdAspirante]) REFERENCES [dbo].[Aca_Aspirante] ([IdInstitucion], [IdAspirante]),
    CONSTRAINT [FK_Aca_Admision_Aca_Catalogo] FOREIGN KEY ([IdCatalogo_Grupo_Fami_convivencia]) REFERENCES [dbo].[Aca_Catalogo] ([IdCatalogo]),
    CONSTRAINT [FK_Aca_Admision_Aca_Catalogo1] FOREIGN KEY ([IdCatalogo_Tipo_Religion]) REFERENCES [dbo].[Aca_Catalogo] ([IdCatalogo]),
    CONSTRAINT [FK_Aca_Admision_Aca_Catalogo2] FOREIGN KEY ([IdCatalogo_Tipo_Sangre]) REFERENCES [dbo].[Aca_Catalogo] ([IdCatalogo]),
    CONSTRAINT [FK_Aca_Admision_Aca_Catalogo3] FOREIGN KEY ([IdCatalogo_Idioma_Nati]) REFERENCES [dbo].[Aca_Catalogo] ([IdCatalogo]),
    CONSTRAINT [FK_Aca_Admision_Aca_curso] FOREIGN KEY ([IdCurso]) REFERENCES [dbo].[Aca_curso] ([IdCurso])
);



