CREATE TABLE [dbo].[Af_Activo_fijo] (
    [IdEmpresa]                      INT            NOT NULL,
    [IdActivoFijo]                   INT            NOT NULL,
    [CodActivoFijo]                  VARCHAR (50)   NOT NULL,
    [IdTipoDepreciacion]             INT            NOT NULL,
    [Af_Nombre]                      VARCHAR (500)  NOT NULL,
    [IdActijoFijoTipo]               INT            NOT NULL,
    [IdSucursal]                     INT            NOT NULL,
    [IdCatalogo_Marca]               VARCHAR (35)   NOT NULL,
    [IdCatalogo_Modelo]              VARCHAR (35)   NOT NULL,
    [Af_NumSerie]                    VARCHAR (50)   NULL,
    [IdCatalogo_Color]               VARCHAR (35)   NOT NULL,
    [IdTipoCatalogo_Ubicacion]       VARCHAR (35)   NULL,
    [Af_fecha_compra]                DATETIME       NOT NULL,
    [Af_fecha_ini_depre]             DATETIME       NOT NULL,
    [Af_fecha_fin_depre]             DATETIME       NOT NULL,
    [Af_Costo_historico]             FLOAT (53)     NOT NULL,
    [Af_costo_compra]                FLOAT (53)     NOT NULL,
    [Af_Depreciacion_acum]           FLOAT (53)     NULL,
    [Af_Vida_Util]                   INT            NOT NULL,
    [Af_Meses_depreciar]             INT            NOT NULL,
    [Af_porcentaje_deprec]           FLOAT (53)     NOT NULL,
    [Af_observacion]                 VARCHAR (1000) NOT NULL,
    [Af_NumPlaca]                    VARCHAR (20)   NULL,
    [Af_Anio_fabrica]                INT            NULL,
    [Estado]                         CHAR (1)       NOT NULL,
    [MotiAnula]                      VARCHAR (100)  NULL,
    [Af_foto]                        IMAGE          NULL,
    [Af_DescripcionCorta]            VARCHAR (50)   NULL,
    [IdPeriodoDeprec]                VARCHAR (20)   NULL,
    [Af_Codigo_Parte]                VARCHAR (50)   NULL,
    [Af_Codigo_Barra]                VARCHAR (50)   NULL,
    [Af_DescripcionTecnica]          VARCHAR (200)  NULL,
    [IdProveedor]                    NUMERIC (18)   NULL,
    [Af_FechaPoliza]                 DATETIME       NULL,
    [Af_ValorPoliza]                 FLOAT (53)     NULL,
    [Af_ValorVenta]                  FLOAT (53)     NULL,
    [Af_NumPoliza]                   VARCHAR (50)   NULL,
    [Af_Fecha_Venta]                 DATETIME       NULL,
    [Af_Fecha_Vencimiento]           DATETIME       NULL,
    [Af_Fecha_Retiro]                DATETIME       NULL,
    [Estado_Proceso]                 VARCHAR (35)   NULL,
    [Af_ValorSalvamento]             FLOAT (53)     NULL,
    [Af_ValorResidual]               FLOAT (53)     NULL,
    [IdEmpresa_oc]                   INT            NULL,
    [IdSucursal_oc]                  INT            NULL,
    [IdOrdenCompra]                  NUMERIC (18)   NULL,
    [Secuencia_oc]                   INT            NULL,
    [IdProducto]                     NUMERIC (18)   NULL,
    [numDocumento]                   VARCHAR (50)   NULL,
    [Cantidad]                       FLOAT (53)     NULL,
    [Costo_uni]                      FLOAT (53)     NULL,
    [SubTotal]                       FLOAT (53)     NULL,
    [valor_Iva]                      FLOAT (53)     NULL,
    [Total]                          FLOAT (53)     NULL,
    [IdEmpresa_Ogiro]                INT            NULL,
    [IdCbteCble_Ogiro]               NUMERIC (18)   NULL,
    [IdTipoCbte_Ogiro]               INT            NULL,
    [IdOrden_giro_Tipo]              VARCHAR (5)    NULL,
    [IdUsuario]                      VARCHAR (20)   NULL,
    [Fecha_Transac]                  DATETIME       NULL,
    [IdUsuarioUltMod]                VARCHAR (20)   NULL,
    [Fecha_UltMod]                   DATETIME       NULL,
    [IdUsuarioUltAnu]                VARCHAR (20)   NULL,
    [Fecha_UltAnu]                   DATETIME       NULL,
    [nom_pc]                         VARCHAR (50)   NULL,
    [ip]                             VARCHAR (25)   NULL,
    [Af_NumSerie_Motor]              VARCHAR (50)   NULL,
    [Af_NumSerie_Chasis]             VARCHAR (50)   NULL,
    [IdCategoriaAF]                  INT            NULL,
    [IdDepartamento]                 INT            NULL,
    [IdEncargado]                    DECIMAL (18)   NULL,
    [IdCentroCosto]                  VARCHAR (20)   NULL,
    [IdUnidadFact_cat]               VARCHAR (50)   NULL,
    [Af_ValorUnidad_Actu]            FLOAT (53)     NULL,
    [Af_fecha_vigencia_desde]        DATETIME       NULL,
    [Subtotal_Prima]                 FLOAT (53)     NULL,
    [Iva_Prima]                      FLOAT (53)     NULL,
    [Prima]                          FLOAT (53)     NULL,
    [IdCentroCosto_sub_centro_costo] VARCHAR (20)   NULL,
    [Af_Capacidad]                   VARCHAR (50)   NULL,
    [Es_carroceria]                  BIT            NULL,
    CONSTRAINT [PK_Af_Activo_fijo_1] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdActivoFijo] ASC),
    CONSTRAINT [FK_Af_Activo_fijo_Af_Activo_fijo_Categoria] FOREIGN KEY ([IdEmpresa], [IdCategoriaAF]) REFERENCES [dbo].[Af_Activo_fijo_Categoria] ([IdEmpresa], [IdCategoriaAF]),
    CONSTRAINT [FK_Af_Activo_fijo_Af_Activo_fijo_tipo] FOREIGN KEY ([IdEmpresa], [IdActijoFijoTipo]) REFERENCES [dbo].[Af_Activo_fijo_tipo] ([IdEmpresa], [IdActijoFijoTipo]),
    CONSTRAINT [FK_Af_Activo_fijo_Af_Catalogo] FOREIGN KEY ([IdTipoCatalogo_Ubicacion]) REFERENCES [dbo].[Af_Catalogo] ([IdCatalogo]),
    CONSTRAINT [FK_Af_Activo_fijo_Af_Catalogo1] FOREIGN KEY ([IdCatalogo_Marca]) REFERENCES [dbo].[Af_Catalogo] ([IdCatalogo]),
    CONSTRAINT [FK_Af_Activo_fijo_Af_Catalogo2] FOREIGN KEY ([IdCatalogo_Modelo]) REFERENCES [dbo].[Af_Catalogo] ([IdCatalogo]),
    CONSTRAINT [FK_Af_Activo_fijo_Af_Catalogo3] FOREIGN KEY ([IdCatalogo_Color]) REFERENCES [dbo].[Af_Catalogo] ([IdCatalogo]),
    CONSTRAINT [FK_Af_Activo_fijo_Af_Catalogo4] FOREIGN KEY ([Estado_Proceso]) REFERENCES [dbo].[Af_Catalogo] ([IdCatalogo]),
    CONSTRAINT [FK_Af_Activo_fijo_Af_Departamento] FOREIGN KEY ([IdEmpresa], [IdDepartamento]) REFERENCES [dbo].[Af_Departamento] ([IdEmpresa], [IdDepartamento]),
    CONSTRAINT [FK_Af_Activo_fijo_Af_Encargado] FOREIGN KEY ([IdEmpresa], [IdEncargado]) REFERENCES [dbo].[Af_Encargado] ([IdEmpresa], [IdEncargado]),
    CONSTRAINT [FK_Af_Activo_fijo_Af_PeriodoDepreciacion] FOREIGN KEY ([IdPeriodoDeprec]) REFERENCES [dbo].[Af_PeriodoDepreciacion] ([IdPeriodoDeprec]),
    CONSTRAINT [FK_Af_Activo_fijo_Af_Tipo_Depreciacion] FOREIGN KEY ([IdTipoDepreciacion]) REFERENCES [dbo].[Af_Tipo_Depreciacion] ([IdTipoDepreciacion]),
    CONSTRAINT [FK_Af_Activo_fijo_cp_proveedor] FOREIGN KEY ([IdEmpresa], [IdProveedor]) REFERENCES [dbo].[cp_proveedor] ([IdEmpresa], [IdProveedor]),
    CONSTRAINT [FK_Af_Activo_fijo_in_Producto] FOREIGN KEY ([IdEmpresa], [IdProducto]) REFERENCES [dbo].[in_Producto] ([IdEmpresa], [IdProducto]),
    CONSTRAINT [FK_Af_Activo_fijo_tb_empresa] FOREIGN KEY ([IdEmpresa]) REFERENCES [dbo].[tb_empresa] ([IdEmpresa]),
    CONSTRAINT [FK_Af_Activo_fijo_tb_sucursal] FOREIGN KEY ([IdEmpresa], [IdSucursal]) REFERENCES [dbo].[tb_sucursal] ([IdEmpresa], [IdSucursal])
);













