CREATE TABLE [dbo].[com_ordencompra_local] (
    [IdEmpresa]              INT            NOT NULL,
    [IdSucursal]             INT            NOT NULL,
    [IdOrdenCompra]          NUMERIC (18)   NOT NULL,
    [IdProveedor]            NUMERIC (18)   NOT NULL,
    [oc_NumDocumento]        VARCHAR (50)   NOT NULL,
    [Tipo]                   VARCHAR (5)    NOT NULL,
    [IdTerminoPago]          VARCHAR (25)   NOT NULL,
    [oc_plazo]               INT            NOT NULL,
    [oc_fecha]               DATETIME       NOT NULL,
    [oc_flete]               FLOAT (53)     NOT NULL,
    [oc_observacion]         VARCHAR (1000) NOT NULL,
    [Estado]                 CHAR (1)       NOT NULL,
    [IdEstadoAprobacion_cat] VARCHAR (25)   NOT NULL,
    [co_fecha_aprobacion]    DATETIME       NULL,
    [IdUsuario_Aprueba]      VARCHAR (20)   NULL,
    [IdUsuario_Reprue]       VARCHAR (20)   NULL,
    [co_fechaReproba]        DATETIME       NULL,
    [Fecha_Transac]          DATETIME       NULL,
    [Fecha_UltMod]           DATETIME       NULL,
    [IdUsuarioUltMod]        CHAR (20)      NULL,
    [FechaHoraAnul]          DATETIME       NULL,
    [IdUsuarioUltAnu]        CHAR (20)      NULL,
    [IdEstadoRecepcion_cat]  VARCHAR (25)   NOT NULL,
    [AfectaCosto]            CHAR (1)       NULL,
    [MotivoAnulacion]        VARCHAR (500)  NULL,
    [MotivoReprobacion]      VARCHAR (500)  NULL,
    [Solicitante]            VARCHAR (200)  NULL,
    [IdSolicitante]          NUMERIC (18)   NULL,
    [IdDepartamento]         NUMERIC (18)   NULL,
    [IdUsuario]              VARCHAR (25)   NULL,
    [IdMotivo]               INT            NULL,
    [oc_fechaVencimiento]    DATETIME       NULL,
    [IdEstado_cierre]        VARCHAR (25)   NULL,
    [IdComprador]            NUMERIC (18)   NOT NULL,
    CONSTRAINT [PK_in_ordencompra_local] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdSucursal] ASC, [IdOrdenCompra] ASC),
    CONSTRAINT [FK_com_ordencompra_local_com_catalogo] FOREIGN KEY ([IdEstadoAprobacion_cat]) REFERENCES [dbo].[com_catalogo] ([IdCatalogocompra]),
    CONSTRAINT [FK_com_ordencompra_local_com_catalogo1] FOREIGN KEY ([IdEstadoRecepcion_cat]) REFERENCES [dbo].[com_catalogo] ([IdCatalogocompra]),
    CONSTRAINT [FK_com_ordencompra_local_com_comprador] FOREIGN KEY ([IdEmpresa], [IdComprador]) REFERENCES [dbo].[com_comprador] ([IdEmpresa], [IdComprador]),
    CONSTRAINT [FK_com_ordencompra_local_com_departamento] FOREIGN KEY ([IdEmpresa], [IdDepartamento]) REFERENCES [dbo].[com_departamento] ([IdEmpresa], [IdDepartamento]),
    CONSTRAINT [FK_com_ordencompra_local_com_estado_cierre] FOREIGN KEY ([IdEstado_cierre]) REFERENCES [dbo].[com_estado_cierre] ([IdEstado_cierre]),
    CONSTRAINT [FK_com_ordencompra_local_com_Motivo_Orden_Compra] FOREIGN KEY ([IdEmpresa], [IdMotivo]) REFERENCES [dbo].[com_Motivo_Orden_Compra] ([IdEmpresa], [IdMotivo]),
    CONSTRAINT [FK_com_ordencompra_local_com_solicitante] FOREIGN KEY ([IdEmpresa], [IdSolicitante]) REFERENCES [dbo].[com_solicitante] ([IdEmpresa], [IdSolicitante]),
    CONSTRAINT [FK_com_ordencompra_local_com_TerminoPago] FOREIGN KEY ([IdTerminoPago]) REFERENCES [dbo].[com_TerminoPago] ([IdTerminoPago]),
    CONSTRAINT [FK_com_ordencompra_local_cp_proveedor] FOREIGN KEY ([IdEmpresa], [IdProveedor]) REFERENCES [dbo].[cp_proveedor] ([IdEmpresa], [IdProveedor]),
    CONSTRAINT [FK_com_ordencompra_local_tb_sucursal] FOREIGN KEY ([IdEmpresa], [IdSucursal]) REFERENCES [dbo].[tb_sucursal] ([IdEmpresa], [IdSucursal])
);

