CREATE TABLE [dbo].[fa_guia_remision] (
    [IdEmpresa]           INT            NOT NULL,
    [IdSucursal]          INT            NOT NULL,
    [IdBodega]            INT            NOT NULL,
    [IdGuiaRemision]      NUMERIC (18)   NOT NULL,
    [CodGuiaRemision]     VARCHAR (20)   NOT NULL,
    [CodDocumentoTipo]    VARCHAR (20)   NULL,
    [Serie1]              VARCHAR (3)    NULL,
    [Serie2]              VARCHAR (3)    NULL,
    [NumGuia_Preimpresa]  VARCHAR (20)   NULL,
    [NUAutorizacion]      VARCHAR (50)   NULL,
    [Fecha_Autorizacion]  DATETIME       NULL,
    [IdCliente]           NUMERIC (18)   NOT NULL,
    [IdVendedor]          INT            NOT NULL,
    [IdTransportista]     NUMERIC (18)   NOT NULL,
    [gi_fecha]            DATETIME       NOT NULL,
    [gi_plazo]            NUMERIC (10)   NULL,
    [gi_fech_venc]        DATETIME       NULL,
    [gi_Observacion]      VARCHAR (1000) NULL,
    [gi_TotalKilos]       FLOAT (53)     NULL,
    [gi_TotalQuintales]   FLOAT (53)     NULL,
    [IdUsuario]           VARCHAR (20)   NOT NULL,
    [Fecha_Transac]       DATETIME       NOT NULL,
    [IdUsuarioUltMod]     VARCHAR (20)   NULL,
    [Fecha_UltMod]        DATETIME       NULL,
    [IdUsuarioUltAnu]     VARCHAR (20)   NULL,
    [Fecha_UltAnu]        DATETIME       NULL,
    [nom_pc]              VARCHAR (50)   NOT NULL,
    [ip]                  VARCHAR (25)   NOT NULL,
    [Estado]              CHAR (1)       NOT NULL,
    [MotiAnula]           VARCHAR (200)  NULL,
    [Impreso]             CHAR (1)       NULL,
    [IdPeriodo]           INT            NULL,
    [gi_flete]            FLOAT (53)     NOT NULL,
    [gi_interes]          FLOAT (53)     NOT NULL,
    [gi_seguro]           FLOAT (53)     NOT NULL,
    [gi_OtroValor1]       FLOAT (53)     NOT NULL,
    [gi_OtroValor2]       FLOAT (53)     NOT NULL,
    [gi_FechaIniTraslado] DATETIME       NOT NULL,
    [gi_FechaFinTraslado] DATETIME       NOT NULL,
    [placa]               VARCHAR (20)   NOT NULL,
    [ruta]                VARCHAR (300)  NULL,
    [Direccion_Origen]    VARCHAR (300)  NOT NULL,
    [Direccion_Destino]   VARCHAR (300)  NOT NULL,
    [idMotivo_traslado]   INT            NULL,
    CONSTRAINT [PK_fa_guia_remision] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdSucursal] ASC, [IdBodega] ASC, [IdGuiaRemision] ASC),
    CONSTRAINT [FK_fa_guia_remision_ct_periodo] FOREIGN KEY ([IdEmpresa], [IdPeriodo]) REFERENCES [dbo].[ct_periodo] ([IdEmpresa], [IdPeriodo]),
    CONSTRAINT [FK_fa_guia_remision_fa_cliente] FOREIGN KEY ([IdEmpresa], [IdCliente]) REFERENCES [dbo].[fa_cliente] ([IdEmpresa], [IdCliente]),
    CONSTRAINT [FK_fa_guia_remision_fa_Vendedor] FOREIGN KEY ([IdEmpresa], [IdVendedor]) REFERENCES [dbo].[fa_Vendedor] ([IdEmpresa], [IdVendedor]),
    CONSTRAINT [FK_fa_guia_remision_tb_bodega] FOREIGN KEY ([IdEmpresa], [IdSucursal], [IdBodega]) REFERENCES [dbo].[tb_bodega] ([IdEmpresa], [IdSucursal], [IdBodega]),
    CONSTRAINT [FK_fa_guia_remision_tb_sis_Documento_Tipo_Talonario] FOREIGN KEY ([IdEmpresa], [CodDocumentoTipo], [Serie2], [Serie1], [NumGuia_Preimpresa]) REFERENCES [dbo].[tb_sis_Documento_Tipo_Talonario] ([IdEmpresa], [CodDocumentoTipo], [PuntoEmision], [Establecimiento], [NumDocumento]),
    CONSTRAINT [FK_fa_guia_remision_tb_transportista] FOREIGN KEY ([IdEmpresa], [IdTransportista]) REFERENCES [dbo].[tb_transportista] ([IdEmpresa], [IdTransportista])
);







