CREATE TABLE [dbo].[fa_orden_Desp] (
    [IdEmpresa]         INT            NOT NULL,
    [IdSucursal]        INT            NOT NULL,
    [IdBodega]          INT            NOT NULL,
    [IdOrdenDespacho]   NUMERIC (18)   NOT NULL,
    [CodOrdenDespacho]  VARCHAR (20)   NOT NULL,
    [IdCliente]         NUMERIC (18)   NOT NULL,
    [IdVendedor]        INT            NOT NULL,
    [IdTransportista]   NUMERIC (18)   NOT NULL,
    [od_fecha]          DATETIME       NOT NULL,
    [od_plazo]          INT            NOT NULL,
    [od_fech_venc]      DATETIME       NOT NULL,
    [od_Observacion]    VARCHAR (1000) NOT NULL,
    [od_TotalKilos]     FLOAT (53)     NOT NULL,
    [od_TotalQuintales] FLOAT (53)     NOT NULL,
    [IdUsuario]         VARCHAR (20)   NULL,
    [Fecha_Transac]     DATETIME       NULL,
    [IdUsuarioUltMod]   VARCHAR (20)   NULL,
    [Fecha_UltMod]      DATETIME       NULL,
    [IdUsuarioUltAnu]   VARCHAR (20)   NULL,
    [Fecha_UltAnu]      DATETIME       NULL,
    [MotivoAnu]         VARCHAR (200)  NULL,
    [nom_pc]            VARCHAR (50)   NULL,
    [ip]                VARCHAR (25)   NULL,
    [Estado]            CHAR (1)       NOT NULL,
    [od_DespAbierto]    CHAR (1)       NULL,
    CONSTRAINT [PK_fa_orden_Desp] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdSucursal] ASC, [IdBodega] ASC, [IdOrdenDespacho] ASC),
    CONSTRAINT [FK_fa_orden_Desp_fa_cliente] FOREIGN KEY ([IdEmpresa], [IdCliente]) REFERENCES [dbo].[fa_cliente] ([IdEmpresa], [IdCliente]),
    CONSTRAINT [FK_fa_orden_Desp_fa_Vendedor] FOREIGN KEY ([IdEmpresa], [IdVendedor]) REFERENCES [dbo].[fa_Vendedor] ([IdEmpresa], [IdVendedor]),
    CONSTRAINT [FK_fa_orden_Desp_tb_bodega] FOREIGN KEY ([IdEmpresa], [IdSucursal], [IdBodega]) REFERENCES [dbo].[tb_bodega] ([IdEmpresa], [IdSucursal], [IdBodega])
);

