CREATE TABLE [dbo].[fa_pedido] (
    [IdEmpresa]           INT            NOT NULL,
    [IdSucursal]          INT            NOT NULL,
    [IdBodega]            INT            NOT NULL,
    [IdPedido]            NUMERIC (18)   NOT NULL,
    [IdCliente]           NUMERIC (18)   NOT NULL,
    [IdVendedor]          INT            NOT NULL,
    [cp_fecha]            DATETIME       NOT NULL,
    [cp_diasPlazo]        INT            NOT NULL,
    [cp_fechaVencimiento] DATETIME       NOT NULL,
    [cp_observacion]      VARCHAR (1000) NOT NULL,
    [cp_tipopago]         CHAR (3)       NOT NULL,
    [IdEstadoAprobacion]  CHAR (1)       NOT NULL,
    [IdUsuario]           VARCHAR (20)   NULL,
    [Fecha_Transac]       DATETIME       NULL,
    [IdUsuarioUltMod]     VARCHAR (20)   NULL,
    [Fecha_UltMod]        DATETIME       NULL,
    [IdUsuarioUltAnu]     VARCHAR (20)   NULL,
    [Fecha_UltAnu]        DATETIME       NULL,
    [nom_pc]              VARCHAR (50)   NULL,
    [ip]                  VARCHAR (25)   NULL,
    [Estado]              CHAR (1)       NOT NULL,
    [interes]             FLOAT (53)     NOT NULL,
    [transporte]          FLOAT (53)     NOT NULL,
    [otro1]               FLOAT (53)     NOT NULL,
    [otro2]               FLOAT (53)     NOT NULL,
    [MotivoAnulacion]     VARCHAR (500)  NULL,
    [CodPedido]           VARCHAR (20)   NULL,
    [Entregado]           CHAR (1)       NULL,
    [IdEstadoProduccion]  VARCHAR (15)   NULL,
    CONSTRAINT [PK_fa_pedido] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdSucursal] ASC, [IdBodega] ASC, [IdPedido] ASC),
    CONSTRAINT [FK_fa_pedido_fa_cliente] FOREIGN KEY ([IdEmpresa], [IdCliente]) REFERENCES [dbo].[fa_cliente] ([IdEmpresa], [IdCliente]),
    CONSTRAINT [FK_fa_pedido_fa_pedido_estadoAprobacion] FOREIGN KEY ([IdEstadoAprobacion]) REFERENCES [dbo].[fa_pedido_estadoAprobacion] ([IdEstadoAprobacion]),
    CONSTRAINT [FK_fa_pedido_fa_Vendedor] FOREIGN KEY ([IdEmpresa], [IdVendedor]) REFERENCES [dbo].[fa_Vendedor] ([IdEmpresa], [IdVendedor]),
    CONSTRAINT [FK_fa_pedido_tb_bodega] FOREIGN KEY ([IdEmpresa], [IdSucursal], [IdBodega]) REFERENCES [dbo].[tb_bodega] ([IdEmpresa], [IdSucursal], [IdBodega])
);

