CREATE TABLE [dbo].[imp_ordencompra_ext] (
    [IdEmpresa]               INT            NOT NULL,
    [IdSucusal]               INT            NOT NULL,
    [IdOrdenCompraExt]        NUMERIC (18)   NOT NULL,
    [CodOrdenCompraExt]       VARCHAR (20)   NULL,
    [ci_plazo]                INT            NULL,
    [ci_fecha]                DATETIME       NULL,
    [IdProveedor]             NUMERIC (18)   NULL,
    [NumFacturaProvedor]      VARCHAR (50)   NULL,
    [ci_Observacion]          NVARCHAR (200) NULL,
    [Fecha_Transac]           DATETIME       NULL,
    [Estado]                  CHAR (1)       NULL,
    [IdUsuario]               VARCHAR (20)   NULL,
    [ci_costo_Flete_externo]  FLOAT (53)     NULL,
    [ci_costo_Flete_interno]  FLOAT (53)     NULL,
    [ci_costoSeguro]          FLOAT (53)     NULL,
    [ci_costoCif]             FLOAT (53)     NULL,
    [ci_GastosTotales]        FLOAT (53)     NULL,
    [IdVia]                   VARCHAR (15)   NULL,
    [ci_fecha_aprobacion]     DATETIME       NULL,
    [ci_fechaFactProv]        DATETIME       NULL,
    [ci_fechVenciFact]        DATETIME       NULL,
    [ci_fechaDespProv]        DATETIME       NULL,
    [ci_fechaRecEmb]          DATETIME       NULL,
    [ci_fechaAproxSal]        DATETIME       NULL,
    [ci_fec_est_llegada]      DATETIME       NULL,
    [ci_fecha_llegada_Bodega] DATETIME       NULL,
    [ci_fechaRealArri]        DATETIME       NULL,
    [ci_fechaDocAAA]          DATETIME       NULL,
    [ci_fecha_liquidacion]    DATETIME       NULL,
    [ci_fecha_sal_aduana]     DATETIME       NULL,
    [ci_diasFecFacProv]       INT            NULL,
    [ci_diasFecDespProv]      INT            NULL,
    [ci_diasFecAproxSal]      INT            NULL,
    [ci_diasFecAproxLleg]     INT            NULL,
    [ci_diasNaciona]          INT            NULL,
    [ci_fecha_pago]           DATETIME       NULL,
    [ci_fecha_salida]         DATETIME       NULL,
    [ci_fecha_llegada]        DATETIME       NULL,
    [ci_fecha_despacho]       DATETIME       NULL,
    [ci_dias_estimados]       INT            NULL,
    [ci_valor_derecho]        FLOAT (53)     NULL,
    [IdMonedaOrigen]          INT            NULL,
    [IdMonedaCambiaria]       INT            NULL,
    [ci_EquivalenciaMoneda]   FLOAT (53)     NULL,
    [IdCicloImportacion]      VARCHAR (15)   NULL,
    [IdCtaCble_Inven]         VARCHAR (20)   NULL,
    [IdCtaCble_import]        VARCHAR (20)   NULL,
    [IdEmbarcador]            INT            NULL,
    [ci_contabilizada]        CHAR (1)       NULL,
    [ci_Idfecha_Bodega]       NUMERIC (18)   NULL,
    [ci_fechaRegsis]          DATETIME       NULL,
    [ci_ultFechaModi]         DATETIME       NULL,
    [ci_ultUserModi]          CHAR (20)      NULL,
    [IdPaisOrgCarga]          VARCHAR (10)   NULL,
    [IdPaisProceCarga]        VARCHAR (10)   NULL,
    [ci_dui]                  VARCHAR (20)   NULL,
    [ci_fechaHoraAnul]        DATETIME       NULL,
    [ci_userAnul]             CHAR (20)      NULL,
    [ci_anio]                 INT            NULL,
    [ci_mes]                  INT            NULL,
    [ci_FechaCosteo]          DATETIME       NULL,
    [IdUsuarioUltMod]         VARCHAR (20)   NULL,
    [Fecha_UltMod]            DATETIME       NULL,
    [IdUsuarioUltAnu]         VARCHAR (20)   NULL,
    [Fecha_UltAnu]            DATETIME       NULL,
    [nom_pc]                  VARCHAR (50)   NULL,
    [ip]                      VARCHAR (25)   NULL,
    [MotiAnula]               VARCHAR (200)  NULL,
    [ci_tonelaje]             FLOAT (53)     NULL,
    [ci_lugarEmbarque]        VARCHAR (100)  NULL,
    [Buque]                   VARCHAR (50)   NULL,
    [Naviera]                 VARCHAR (50)   NULL,
    [ci_Total]                FLOAT (53)     NULL,
    [CFR]                     FLOAT (53)     NULL,
    [IdCategoria]             VARCHAR (25)   NULL,
    [IdEstadoLiquidacion]     VARCHAR (15)   NULL,
    [ci_diasEmbarque]         INT            NULL,
    [ci_fechaFirmaContrato]   DATETIME       NULL,
    [Tipo_Importacion]        VARCHAR (50)   NULL,
    [Fecha_Maximo_Despacho]   DATETIME       NULL,
    CONSTRAINT [PK_imp_ordencompra_ext] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdSucusal] ASC, [IdOrdenCompraExt] ASC),
    CONSTRAINT [FK_imp_ordencompra_ext_cp_proveedor] FOREIGN KEY ([IdEmpresa], [IdProveedor]) REFERENCES [dbo].[cp_proveedor] ([IdEmpresa], [IdProveedor]),
    CONSTRAINT [FK_imp_ordencompra_ext_ct_plancta] FOREIGN KEY ([IdEmpresa], [IdCtaCble_Inven]) REFERENCES [dbo].[ct_plancta] ([IdEmpresa], [IdCtaCble]),
    CONSTRAINT [FK_imp_ordencompra_ext_ct_plancta1] FOREIGN KEY ([IdEmpresa], [IdCtaCble_import]) REFERENCES [dbo].[ct_plancta] ([IdEmpresa], [IdCtaCble]),
    CONSTRAINT [FK_imp_ordencompra_ext_imp_Embarcador] FOREIGN KEY ([IdEmbarcador], [IdEmpresa]) REFERENCES [dbo].[imp_Embarcador] ([IdEmbarcador], [IdEmpresa]),
    CONSTRAINT [FK_imp_ordencompra_ext_tb_moneda] FOREIGN KEY ([IdMonedaOrigen]) REFERENCES [dbo].[tb_moneda] ([IdMoneda]),
    CONSTRAINT [FK_imp_ordencompra_ext_tb_moneda1] FOREIGN KEY ([IdMonedaCambiaria]) REFERENCES [dbo].[tb_moneda] ([IdMoneda]),
    CONSTRAINT [FK_imp_ordencompra_ext_tb_pais] FOREIGN KEY ([IdPaisOrgCarga]) REFERENCES [dbo].[tb_pais] ([IdPais]),
    CONSTRAINT [FK_imp_ordencompra_ext_tb_pais1] FOREIGN KEY ([IdPaisProceCarga]) REFERENCES [dbo].[tb_pais] ([IdPais]),
    CONSTRAINT [FK_imp_ordencompra_ext_tb_sucursal] FOREIGN KEY ([IdEmpresa], [IdSucusal]) REFERENCES [dbo].[tb_sucursal] ([IdEmpresa], [IdSucursal])
);

