CREATE TABLE [dbo].[prod_CompraChatarra_CusTalme] (
    [IdEmpresa]         INT           NOT NULL,
    [IdLiquidacion]     NUMERIC (18)  NOT NULL,
    [IdProveedor_Presu] NUMERIC (18)  NULL,
    [IdProveedor]       NUMERIC (18)  NULL,
    [Fecha]             DATETIME      NULL,
    [Beneficiario]      VARCHAR (150) NULL,
    [Placa]             VARCHAR (50)  NULL,
    [IdTipoChatarra]    INT           NULL,
    [PrecioChatarra]    FLOAT (53)    NULL,
    [TLlenoKg]          FLOAT (53)    NULL,
    [TVacionKg]         FLOAT (53)    NULL,
    [TMermaKg]          FLOAT (53)    NULL,
    [TNetokg]           FLOAT (53)    NULL,
    [Subtotal]          FLOAT (53)    NULL,
    [Descuento]         FLOAT (53)    NULL,
    [Total]             FLOAT (53)    NULL,
    [IdUsuario]         VARCHAR (20)  NULL,
    [Fecha_Transa]      DATETIME      NULL,
    [IdUsuarioUltMod]   VARCHAR (20)  NULL,
    [Fecha_UltMod]      DATETIME      NULL,
    [IdUsuarioUltAnu]   VARCHAR (20)  NULL,
    [Fecha_UltAnu]      DATETIME      NULL,
    [MotiAnula]         VARCHAR (200) NULL,
    [nom_pc]            VARCHAR (50)  NULL,
    [ip]                VARCHAR (25)  NULL,
    [Estado]            CHAR (1)      NULL,
    [IdProducto_Compra] NUMERIC (18)  NULL,
    [IdModeloProd]      INT           NULL,
    CONSTRAINT [PK_prod_CompraChatarra_CusTalme] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdLiquidacion] ASC)
);

