CREATE TABLE [dbo].[prod_GestionProductivaLaminado_CusTalme] (
    [IdEmpresa]               INT          NOT NULL,
    [IdGestionProductiva]     NUMERIC (18) NOT NULL,
    [IdTurno]                 INT          NULL,
    [IdEmpleado_JefeTurno]    NUMERIC (18) NULL,
    [IdProducto_MateriaPrima] NUMERIC (18) NULL,
    [Id_Bobina]               VARCHAR (50) NULL,
    [Num_Orden]               VARCHAR (50) NULL,
    [kg_Cargados]             FLOAT (53)   NULL,
    [kg_producidos]           FLOAT (53)   NULL,
    [IdProducto_Producido1]   NUMERIC (18) NULL,
    [unidades_prd_1]          FLOAT (53)   NULL,
    [pesokg_prd_1]            FLOAT (53)   NULL,
    [IdProducto_Producido2]   NUMERIC (18) NULL,
    [unidades_prd_2]          FLOAT (53)   NULL,
    [pesokg_prd_2]            FLOAT (53)   NULL,
    [kg_retazo_porcen]        FLOAT (53)   NULL,
    [kg_retazo_valor]         FLOAT (53)   NULL,
    [kg_chatarra_porcen]      FLOAT (53)   NULL,
    [kg_chatarra_valor]       FLOAT (53)   NULL,
    [kg_oxidacion_porcen]     FLOAT (53)   NULL,
    [kg_oxidacion_valor]      FLOAT (53)   NULL,
    [rendi_metal_historico]   FLOAT (53)   NULL,
    [rendi_metal_real]        FLOAT (53)   NULL,
    [rendi_metal_Diferencia]  FLOAT (53)   NULL,
    [consumo_kilowatios]      FLOAT (53)   NULL,
    [consumo_galones]         FLOAT (53)   NULL,
    [cambio_prue_programado]  FLOAT (53)   NULL,
    [cambio_prue_real]        FLOAT (53)   NULL,
    [cambio_prue_porcentaje]  FLOAT (53)   NULL,
    [hora_turno_ini]          TIME (7)     NULL,
    [hora_turno_fin]          TIME (7)     NULL,
    [hora_jornada]            FLOAT (53)   NULL,
    [hora_productiva]         FLOAT (53)   NULL,
    [hora_Paros]              FLOAT (53)   NULL,
    [hora_Neta]               FLOAT (53)   NULL,
    [hora_Hrs_Maquina]        FLOAT (53)   NULL,
    [Ton_Programada]          FLOAT (53)   NULL,
    [Ton_real]                FLOAT (53)   NULL,
    [Ton_Eficiencia]          FLOAT (53)   NULL,
    [Ton_TnHrNeta]            FLOAT (53)   NULL,
    [Ton_kwTon]               FLOAT (53)   NULL,
    [Ton_GlsTon]              FLOAT (53)   NULL,
    [EficienciaProduccion]    FLOAT (53)   NULL,
    [Estado]                  CHAR (1)     NULL,
    [Fecha]                   DATE         NULL,
    CONSTRAINT [PK_prod_GestionProductiva_CusTalme] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdGestionProductiva] ASC)
);

