CREATE TABLE [dbo].[ro_horario] (
    [IdEmpresa]         INT           NOT NULL,
    [IdHorario]         NUMERIC (18)  NOT NULL,
    [HoraIni]           TIME (7)      NULL,
    [HoraFin]           TIME (7)      NULL,
    [ToleranciaEnt]     INT           NULL,
    [ToleranciaSal]     INT           NULL,
    [Estado]            CHAR (1)      NULL,
    [InicioEntrada]     TIME (7)      NULL,
    [FinalEntrada]      TIME (7)      NULL,
    [InicioSal]         TIME (7)      NULL,
    [FinalSalida]       TIME (7)      NULL,
    [SalLunch]          TIME (7)      NULL,
    [RegLunch]          TIME (7)      NULL,
    [Descripcion]       VARCHAR (50)  NULL,
    [MinLunch]          INT           NULL,
    [IdUsuario]         VARCHAR (20)  NULL,
    [Fecha_Transac]     DATETIME      NULL,
    [IdUsuarioUltMod]   VARCHAR (20)  NULL,
    [Fecha_UltMod]      DATETIME      NULL,
    [IdUsuarioUltAnu]   VARCHAR (20)  NULL,
    [Fecha_UltAnu]      DATETIME      NULL,
    [nom_pc]            VARCHAR (50)  NULL,
    [ip]                VARCHAR (25)  NULL,
    [MotiAnula]         VARCHAR (200) NULL,
    [Tolerancia_Hora]   INT           NULL,
    [Tolerancia_Minuto] INT           NULL,
    CONSTRAINT [PK_ro_turno] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdHorario] ASC)
);

