CREATE TABLE [dbo].[ro_nomina_x_horas_extras] (
    [IdEmpresa]                 INT          NOT NULL,
    [IdEmpleado]                NUMERIC (18) NOT NULL,
    [IdNominaTipo]              INT          NOT NULL,
    [IdNominaTipoLiqui]         INT          NOT NULL,
    [IdPeriodo]                 INT          NOT NULL,
    [IdCalendario]              INT          NOT NULL,
    [IdTurno]                   NUMERIC (18) NOT NULL,
    [IdHorario]                 NUMERIC (18) NOT NULL,
    [FechaRegistro]             DATETIME     NOT NULL,
    [time_entrada1]             TIME (0)     NULL,
    [time_entrada2]             TIME (0)     NULL,
    [time_salida1]              TIME (0)     NULL,
    [time_salida2]              TIME (0)     NULL,
    [hora_extra25]              FLOAT (53)   NOT NULL,
    [hora_extra50]              FLOAT (53)   NOT NULL,
    [hora_extra100]             FLOAT (53)   NOT NULL,
    [hora_atraso]               FLOAT (53)   NOT NULL,
    [hora_temprano]             FLOAT (53)   NOT NULL,
    [hora_trabajada]            FLOAT (53)   NOT NULL,
    [FechaIngresa]              DATETIME     NOT NULL,
    [UsuarioIngresa]            VARCHAR (25) NOT NULL,
    [FechaModifica]             DATETIME     NULL,
    [UsuarioModifica]           VARCHAR (25) NULL,
    [es_HorasExtrasAutorizadas] BIT          NULL,
    CONSTRAINT [PK_ro_nomina_x_horas_extras] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdEmpleado] ASC, [IdNominaTipo] ASC, [IdNominaTipoLiqui] ASC, [IdPeriodo] ASC, [IdCalendario] ASC, [IdTurno] ASC),
    CONSTRAINT [FK_ro_nomina_x_horas_extras_ro_empleado] FOREIGN KEY ([IdEmpresa], [IdEmpleado]) REFERENCES [dbo].[ro_empleado] ([IdEmpresa], [IdEmpleado]),
    CONSTRAINT [FK_ro_nomina_x_horas_extras_ro_horario] FOREIGN KEY ([IdEmpresa], [IdHorario]) REFERENCES [dbo].[ro_horario] ([IdEmpresa], [IdHorario]),
    CONSTRAINT [FK_ro_nomina_x_horas_extras_ro_Nomina_Tipoliqui] FOREIGN KEY ([IdEmpresa], [IdNominaTipo], [IdNominaTipoLiqui]) REFERENCES [dbo].[ro_Nomina_Tipoliqui] ([IdEmpresa], [IdNomina_Tipo], [IdNomina_TipoLiqui]),
    CONSTRAINT [FK_ro_nomina_x_horas_extras_ro_periodo] FOREIGN KEY ([IdEmpresa], [IdPeriodo]) REFERENCES [dbo].[ro_periodo] ([IdEmpresa], [IdPeriodo]),
    CONSTRAINT [FK_ro_nomina_x_horas_extras_ro_turno] FOREIGN KEY ([IdEmpresa], [IdTurno]) REFERENCES [dbo].[ro_turno] ([IdEmpresa], [IdTurno])
);

