CREATE TABLE [dbo].[ro_Rol_x_Empleado] (
    [ro_compania]      INT        NOT NULL,
    [ro_sucursal]      INT        NOT NULL,
    [ro_empleado]      INT        NOT NULL,
    [ro_anio]          INT        NOT NULL,
    [ro_mes]           TINYINT    NOT NULL,
    [ro_quincena]      TINYINT    NOT NULL,
    [ro_idRol]         INT        NOT NULL,
    [ro_formapago]     TINYINT    NOT NULL,
    [ro_idTipoIng1]    TINYINT    NULL,
    [ro_stipoIng1]     CHAR (20)  NULL,
    [ro_valorIng1]     FLOAT (53) NULL,
    [ro_idTipoIng2]    TINYINT    NULL,
    [ro_stipoIng2]     CHAR (20)  NULL,
    [ro_valorIng2]     FLOAT (53) NULL,
    [ro_idTipoIng3]    TINYINT    NULL,
    [ro_stipoIng3]     CHAR (20)  NULL,
    [ro_valorIng3]     FLOAT (53) NULL,
    [ro_idTipoIng4]    TINYINT    NULL,
    [ro_stipoIng4]     CHAR (20)  NULL,
    [ro_valorIng4]     FLOAT (53) NULL,
    [ro_idTipoIng5]    TINYINT    NULL,
    [ro_stipoIng5]     CHAR (20)  NULL,
    [ro_valorIng5]     FLOAT (53) NULL,
    [ro_idTipoIng6]    TINYINT    NULL,
    [ro_stipoIng6]     CHAR (20)  NULL,
    [ro_valorIng6]     FLOAT (53) NULL,
    [ro_idTipoIng7]    TINYINT    NULL,
    [ro_stipoIng7]     CHAR (20)  NULL,
    [ro_valorIng7]     FLOAT (53) NULL,
    [ro_idTipoIng8]    TINYINT    NULL,
    [ro_stipoIng8]     CHAR (20)  NULL,
    [ro_valorIng8]     FLOAT (53) NULL,
    [ro_idTipoIng9]    TINYINT    NULL,
    [ro_stipoIng9]     CHAR (20)  NULL,
    [ro_valorIng9]     FLOAT (53) NULL,
    [ro_idTipoIng10]   TINYINT    NULL,
    [ro_stipoIng10]    CHAR (20)  NULL,
    [ro_valorIng10]    FLOAT (53) NULL,
    [ro_totalIng]      FLOAT (53) NULL,
    [ro_idTipoEgr1]    TINYINT    NULL,
    [ro_stipoEgr1]     CHAR (20)  NULL,
    [ro_valorEgr1]     FLOAT (53) NULL,
    [ro_idTipoEgr2]    TINYINT    NULL,
    [ro_stipoEgr2]     CHAR (20)  NULL,
    [ro_valorEgr2]     FLOAT (53) NULL,
    [ro_idTipoEgr3]    TINYINT    NULL,
    [ro_stipoEgr3]     CHAR (20)  NULL,
    [ro_valorEgr3]     FLOAT (53) NULL,
    [ro_idTipoEgr4]    TINYINT    NULL,
    [ro_stipoEgr4]     CHAR (20)  NULL,
    [ro_valorEgr4]     FLOAT (53) NULL,
    [ro_idTipoEgr5]    TINYINT    NULL,
    [ro_stipoEgr5]     CHAR (20)  NULL,
    [ro_valorEgr5]     FLOAT (53) NULL,
    [ro_idTipoEgr6]    TINYINT    NULL,
    [ro_stipoEgr6]     CHAR (20)  NULL,
    [ro_valorEgr6]     FLOAT (53) NULL,
    [ro_idTipoEgr7]    TINYINT    NULL,
    [ro_stipoEgr7]     CHAR (20)  NULL,
    [ro_valorEgr7]     FLOAT (53) NULL,
    [ro_idTipoEgr8]    TINYINT    NULL,
    [ro_stipoEgr8]     CHAR (20)  NULL,
    [ro_valorEgr8]     FLOAT (53) NULL,
    [ro_idTipoEgr9]    TINYINT    NULL,
    [ro_stipoEgr9]     CHAR (20)  NULL,
    [ro_valorEgr9]     FLOAT (53) NULL,
    [ro_idTipoEgr10]   TINYINT    NULL,
    [ro_stipoEgr10]    CHAR (20)  NULL,
    [ro_valorEgr10]    FLOAT (53) NULL,
    [ro_TotalEgr]      FLOAT (53) NULL,
    [ro_NetoARecibir]  FLOAT (53) NULL,
    [ro_cerrado]       CHAR (1)   NULL,
    [ro_contabilizado] CHAR (1)   NULL
);

