CREATE TABLE [dbo].[ro_rdep] (
    [IdEmpresa]                INT           NOT NULL,
    [IdEmpleado]               NUMERIC (18)  NOT NULL,
    [AnioFiscal]               INT           NOT NULL,
    [Observacion]              VARCHAR (255) NULL,
    [Estado]                   VARCHAR (10)  NOT NULL,
    [suelSal]                  FLOAT (53)    NOT NULL,
    [sobSuelComRemu]           FLOAT (53)    NOT NULL,
    [partUtil]                 FLOAT (53)    NOT NULL,
    [intGrabGen]               FLOAT (53)    NOT NULL,
    [impRentEmpl]              FLOAT (53)    NOT NULL,
    [decimTer]                 FLOAT (53)    NOT NULL,
    [decimCuar]                FLOAT (53)    NOT NULL,
    [fondoReserva]             FLOAT (53)    NOT NULL,
    [salarioDigno]             FLOAT (53)    NOT NULL,
    [otrosIngRenGrav]          FLOAT (53)    NOT NULL,
    [ingGravConEsteEmpl]       FLOAT (53)    NOT NULL,
    [sisSalNet]                FLOAT (53)    NOT NULL,
    [apoPerIess]               FLOAT (53)    NOT NULL,
    [aporPerIessConOtrosEmpls] FLOAT (53)    NOT NULL,
    [deducVivienda]            FLOAT (53)    NOT NULL,
    [deducSalud]               FLOAT (53)    NOT NULL,
    [deducEduca]               FLOAT (53)    NOT NULL,
    [deducAliement]            FLOAT (53)    NOT NULL,
    [deducVestim]              FLOAT (53)    NOT NULL,
    [exoDiscap]                FLOAT (53)    NOT NULL,
    [exoTerEd]                 FLOAT (53)    NOT NULL,
    [basImp]                   FLOAT (53)    NOT NULL,
    [impRentCaus]              FLOAT (53)    NOT NULL,
    [valRetAsuOtrosEmpls]      FLOAT (53)    NOT NULL,
    [valImpAsuEsteEmpl]        FLOAT (53)    NOT NULL,
    [valRet]                   FLOAT (53)    NOT NULL,
    [FechaIngresa]             DATETIME      NOT NULL,
    [UsuarioIngresa]           VARCHAR (25)  NOT NULL,
    [FechaModifica]            DATETIME      NULL,
    [UsuarioModifica]          VARCHAR (25)  NULL,
    [IdUsuarioUltAnu]          VARCHAR (20)  NULL,
    [Fecha_UltAnu]             DATETIME      NULL,
    [MotiAnula]                VARCHAR (200) NULL,
    CONSTRAINT [PK_ro_rdep] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdEmpleado] ASC, [AnioFiscal] ASC),
    CONSTRAINT [FK_ro_rdep_ro_empleado] FOREIGN KEY ([IdEmpresa], [IdEmpleado]) REFERENCES [dbo].[ro_empleado] ([IdEmpresa], [IdEmpleado])
);

