CREATE TABLE [dbo].[ro_Solicitud_Vacaciones] (
    [IdEmpresa]          INT           NOT NULL,
    [IdEmpleado]         NUMERIC (18)  NOT NULL,
    [IdSolicitudVaca]    INT           NOT NULL,
    [IdEmpleado_aprue]   NUMERIC (18)  NOT NULL,
    [IdEmpleado_remp]    NUMERIC (18)  NULL,
    [Fecha]              DATETIME      NOT NULL,
    [AnioServicio]       INT           NOT NULL,
    [Dias_q_Corresponde] INT           NOT NULL,
    [Dias_a_disfrutar]   INT           NOT NULL,
    [Dias_pendiente]     INT           NOT NULL,
    [Anio_Desde]         INT           NOT NULL,
    [Anio_Hasta]         INT           NOT NULL,
    [Fecha_Desde]        DATE          NOT NULL,
    [Fecha_Hasta]        DATE          NOT NULL,
    [Fecha_Retorno]      DATE          NOT NULL,
    [Observacion]        VARCHAR (250) NOT NULL,
    [IdEstadoAprobacion] VARCHAR (10)  NOT NULL,
    [IdUsuario]          VARCHAR (20)  NULL,
    [IdUsuario_Anu]      VARCHAR (20)  NULL,
    [FechaAnulacion]     DATETIME      NULL,
    [Fecha_Transac]      DATETIME      NULL,
    [Fecha_UltMod]       DATETIME      NULL,
    [IdUsuarioUltMod]    VARCHAR (20)  NULL,
    [Estado]             CHAR (1)      NULL,
    [MotivoAnulacion]    VARCHAR (250) NULL,
    [ip]                 VARCHAR (50)  NULL,
    [nom_pc]             VARCHAR (50)  NULL,
    CONSTRAINT [PK_ro_Solicitud_Vacaciones_1] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdEmpleado] ASC, [IdSolicitudVaca] ASC, [IdEmpleado_aprue] ASC)
);

