
CREATE TABLE [dbo].[tb_region](
	[Cod_Region] [varchar](10) NOT NULL,
	[Nom_region] [varchar](100) NOT NULL,
 CONSTRAINT [PK_tb_region] PRIMARY KEY CLUSTERED 
(
	[Cod_Region] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]