create view Fj_servindustrias.vwfa_Prefacturacion_x_detalle_x_centro_subCentro as
select Dep.IdEmpresa,Dep.IdPreFacturacion,Dep.IdCentro_Costo,Dep.IdCentroCosto_sub_centro_costo from Fj_servindustrias.fa_pre_facturacion_det_Cobro_x_Depreciacion as Dep
union
select Mov.IdEmpresa,Mov.IdPreFacturacion,Mov.IdCentro_Costo,Mov.IdCentroCosto_sub_centro_costo from Fj_servindustrias.fa_pre_facturacion_det_cobro_x_Movilizacion as Mov
union
select Pol.IdEmpresa,Pol.IdPreFacturacion,Pol.IdCentro_Costo,Pol.IdCentroCosto_sub_centro_costo from Fj_servindustrias.fa_pre_facturacion_det_cobro_x_Poliza as Pol
union
select Uni_Consum.IdEmpresa,Uni_Consum.IdPreFacturacion,Uni_Consum.IdCentroCosto,Uni_Consum.IdCentroCosto_sub_centro_costo from Fj_servindustrias.fa_pre_facturacion_det_cobro_x_Unidades_Consumidas as Uni_Consum
union
select Egr_Bod.IdEmpresa,Egr_Bod.IdPreFacturacion,Egr_Bod.IdCentro_Costo,Egr_Bod.IdCentroCosto_sub_centro_costo from Fj_servindustrias.fa_pre_facturacion_det_egr_x_bod as Egr_Bod
union
select Gastos.IdEmpresa,Gastos.IdPreFacturacion,Gastos.IdCentro_Costo,Gastos.IdCentroCosto_sub_centro_costo from Fj_servindustrias.fa_pre_facturacion_det_Fact_x_Gastos as Gastos