//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Inventario_Edehsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_Categoria_x_Formula
    {
        public int IdEmpresa { get; set; }
        public int IdCategoria { get; set; }
        public string descripcion_corta { get; set; }
        public Nullable<bool> tiene_longitud { get; set; }
        public Nullable<bool> tiene_espesor { get; set; }
        public Nullable<bool> tiene_ancho { get; set; }
        public Nullable<bool> tiene_alto { get; set; }
        public Nullable<bool> tiene_ceja { get; set; }
        public Nullable<bool> tiene_diametro { get; set; }
        public int densidad { get; set; }
        public string formula { get; set; }
        public bool estado { get; set; }
    }
}
