//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.FJ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntitiesActivoFijo_Reporte_FJ : DbContext
    {
        public EntitiesActivoFijo_Reporte_FJ()
            : base("name=EntitiesActivoFijo_Reporte_FJ")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwACTF_FJ_Rpt002> vwACTF_FJ_Rpt002 { get; set; }
        public DbSet<vwACTF_FJ_Rpt003> vwACTF_FJ_Rpt003 { get; set; }
    
        public virtual ObjectResult<spACTF_Rpt001_Result> spACTF_Rpt001(Nullable<int> idEmpresa, Nullable<System.DateTime> fecha_corte)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var fecha_corteParameter = fecha_corte.HasValue ?
                new ObjectParameter("Fecha_corte", fecha_corte) :
                new ObjectParameter("Fecha_corte", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spACTF_Rpt001_Result>("spACTF_Rpt001", idEmpresaParameter, fecha_corteParameter);
        }
    }
}
