//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.FJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFAC_FJ_Rpt002
    {
        public int IdEmpresa { get; set; }
        public decimal IdLiquidacion { get; set; }
        public int IdPeriodo { get; set; }
        public string cod_liquidacion { get; set; }
        public decimal IdCliente { get; set; }
        public System.DateTime fecha_liqui { get; set; }
        public string Observacion { get; set; }
        public string estado { get; set; }
        public string pe_nombre { get; set; }
        public string pe_apellido { get; set; }
        public int secuencia { get; set; }
        public int IdProducto_Liqui { get; set; }
        public string detalle_x_producto { get; set; }
        public double cantidad { get; set; }
        public double precio { get; set; }
        public double subtotal { get; set; }
        public bool aplica_iva { get; set; }
        public double por_iva { get; set; }
        public double valor_iva { get; set; }
        public double Total_liq { get; set; }
        public string nom_producto_Liqui { get; set; }
    }
}
