//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cus.Erp.Reports.FJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwINV_FJ_Rpt004
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public int IdMovi_inven_tipo { get; set; }
        public decimal IdNumMovi { get; set; }
        public string CodMoviInven { get; set; }
        public string nom_sucursal { get; set; }
        public string nom_bodega { get; set; }
        public System.DateTime Fecha { get; set; }
        public string cod_Movi_Inven_tipo { get; set; }
        public string nom_Movi_Inven_tipo { get; set; }
        public string NumDocumentoRelacionado { get; set; }
        public string NumFactura { get; set; }
        public string Observacion { get; set; }
        public string mv_tipo_movi { get; set; }
        public double CantiIngreso { get; set; }
        public double CantiEgreso { get; set; }
        public double CostoUniIngreso { get; set; }
        public double CostoUniEgreso { get; set; }
        public double Costo { get; set; }
        public string Cod_producto { get; set; }
        public string nom_producto { get; set; }
        public decimal IdProducto { get; set; }
        public Nullable<int> IdEmpresa_oc { get; set; }
        public Nullable<int> IdSucursal_oc { get; set; }
        public Nullable<decimal> IdOrdenCompra { get; set; }
        public Nullable<decimal> IdProveedor { get; set; }
        public string pr_nombre { get; set; }
        public int IdMotivo_Inv { get; set; }
        public string Cod_Motivo_Inv { get; set; }
        public string Desc_mov_inv { get; set; }
        public string IdCentro_costo { get; set; }
        public string Id_SubCentro_costo { get; set; }
        public string nom_Centro_costo { get; set; }
        public string nom_SubCentro_costo { get; set; }
    }
}
