//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Compras
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcom_ListadoMateriales_Detalle
    {
        public int IdEmpresa { get; set; }
        public string CodObra { get; set; }
        public decimal IdOrdenTaller { get; set; }
        public decimal IdListadoMateriales { get; set; }
        public int IdDetalle { get; set; }
        public decimal IdProducto { get; set; }
        public double Unidades { get; set; }
        public double Det_Kg { get; set; }
        public string pr_codigo { get; set; }
        public string pr_descripcion { get; set; }
        public string IdEstadoAprob { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string Estado { get; set; }
        public string lm_Observacion { get; set; }
        public int IdSucursal { get; set; }
        public string Su_Descripcion { get; set; }
        public string IdCategoria { get; set; }
    }
}
