//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Compras
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcom_ordencompra_local_det_x_cant_pedida_solic_compra
    {
        public decimal IdProducto { get; set; }
        public Nullable<double> do_CantidadPedida_Oc { get; set; }
        public Nullable<int> scd_IdEmpresa { get; set; }
        public Nullable<int> scd_IdSucursal { get; set; }
        public Nullable<decimal> scd_IdSolicitudCompra { get; set; }
        public Nullable<int> scd_Secuencia { get; set; }
        public decimal IdProveedor { get; set; }
        public Nullable<int> IdMotivo { get; set; }
    }
}
