//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.Compras
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwcom_dev_compra_det_cant_devuelta_x_prod
    {
        public Nullable<int> ocdet_IdEmpresa { get; set; }
        public Nullable<int> ocdet_IdSucursal { get; set; }
        public Nullable<decimal> ocdet_IdOrdenCompra { get; set; }
        public Nullable<int> ocdet_Secuencia { get; set; }
        public decimal IdProducto { get; set; }
        public Nullable<double> cant_devuelta { get; set; }
    }
}
