//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Erp.Data.CuentasxCobrar_Grafinpren
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxc_Comisiones_x_vendedor
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public decimal IdCobro { get; set; }
        public int Secuencia { get; set; }
        public double Porc_pagado { get; set; }
        public double Valor_pagado { get; set; }
    }
}
